"""Written practice attempts (W03/W04, §20.7.2): staffed-review gating, bounded file validation, private immutable
evidence, mapping with revision concurrency, completeness, and the deadline-safe seal. Images and text here are
synthetic technical fixtures (generated bytes), not learner scripts or academic content."""

from __future__ import annotations

import io
import uuid
from typing import Any

from fastapi.testclient import TestClient
from sqlalchemy import text

from portal_api.db import get_sessionmaker
from tests.test_content_workflow import Staff

PNG_SIGNATURE = bytes([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A])


def _png(w: int = 1200, h: int = 1600, seed: int = 0) -> bytes:
    """A real, fully decodable PNG (a flat synthetic image; the seed makes its bytes unique)."""
    from PIL import Image

    buf = io.BytesIO()
    Image.new("L", (w, h), color=seed % 256).save(buf, format="PNG")
    return buf.getvalue()


def _pdf(pages: int = 1, seed: int = 0) -> bytes:
    """A real PDF with `pages` blank A4 pages (the seed is stored in the metadata to make the bytes unique)."""
    from pypdf import PdfWriter

    w = PdfWriter()
    for _ in range(pages):
        w.add_blank_page(595, 842)
    w.add_metadata({"/Title": f"fixture-{seed}"})
    buf = io.BytesIO()
    w.write(buf)
    return buf.getvalue()


# ------------------------------------------------------------------ fixtures
def _learner(client: TestClient) -> Staff:
    """A learner with the one-time free trial started (practice and written tests need an active plan)."""
    with get_sessionmaker()() as db:
        who = Staff(client, db, [])
    assert client.post("/v1/me/trial", headers=who.headers).status_code == 200
    return who


def _form(client: TestClient, who: Staff, chapter: str, **extra: Any) -> Any:
    body = {"grade": 12, "subject": "chemistry", "chapter_ids": [chapter], "question_count": 1, **extra}
    return client.post("/v1/written/forms", headers={**who.headers, "Idempotency-Key": uuid.uuid4().hex}, json=body)


def _start(client: TestClient, who: Staff, chapter: str, **extra: Any) -> dict[str, Any]:
    f = _form(client, who, chapter, **extra)
    assert f.status_code == 201, f.text
    a = client.post(f"/v1/written/forms/{f.json()['id']}/attempt", headers=who.headers)
    assert a.status_code == 200, a.text
    return dict(a.json())


def _upload(client: TestClient, who: Staff, attempt_id: str, data: bytes) -> Any:
    return client.post(
        f"/v1/written-attempts/{attempt_id}/pages",
        headers={**who.headers, "Content-Type": "application/octet-stream"},
        content=data,
    )


def _map(
    client: TestClient, who: Staff, attempt: dict[str, Any], slots: dict[str, Any], revision: int | None = None
) -> Any:
    return client.put(
        f"/v1/written-attempts/{attempt['id']}/manifest",
        headers=who.headers,
        json={"expected_revision": attempt["manifest_revision"] if revision is None else revision, "slots": slots},
    )


def _seal(client: TestClient, who: Staff, attempt_id: str, revision: int, key: str | None = None) -> Any:
    return client.post(
        f"/v1/written-attempts/{attempt_id}/seal",
        headers=who.headers,
        json={"idempotency_key": key or uuid.uuid4().hex, "expected_revision": revision},
    )


def _shift(attempt_id: str, *, cutoff_offset_s: float) -> None:
    with get_sessionmaker()() as db:
        db.execute(
            text(
                "update written_attempt set upload_cutoff_at = clock_timestamp() + make_interval(secs => :c) "
                "where id = :id"
            ),
            {"c": cutoff_offset_s, "id": attempt_id},
        )
        db.commit()


# ------------------------------------------------------------------ availability and forms
def test_unstaffed_or_unreviewed_written_practice_is_never_offered(
    client: TestClient, published_written: dict[str, Any]
) -> None:
    who = _learner(client)
    av = client.get("/v1/written/availability?grade=12&subject=chemistry", headers=who.headers).json()
    assert av["review_staffed"] is True
    assert next(c for c in av["chapters"] if c["chapter_id"] == published_written["chapter"])["questions"] == 2
    phys = client.get("/v1/written/availability?grade=11&subject=mathematics", headers=who.headers).json()
    assert all(c["questions"] == 0 for c in phys["chapters"])
    too_many = _form(client, who, published_written["chapter"], question_count=3)
    assert too_many.status_code == 422 and too_many.json()["available"] == 2


def test_attempt_shows_questions_and_marks_but_never_rubrics(
    client: TestClient, published_written: dict[str, Any]
) -> None:
    who = _learner(client)
    a = _start(client, who, published_written["chapter"], writing_minutes=30)
    assert a["status"] == "active" and a["writing_deadline_at"] and a["upload_allowance_s"] == 600
    item = a["items"][0]
    assert [s["key"] for s in item["slots"]] == ["1:a", "1:b"] and item["max_units"] == 500
    assert "criteria" not in str(a) and "rubric" not in str(a).lower()


# ------------------------------------------------------------------ evidence
def test_uploads_are_private_validated_and_deduplicated_within_the_attempt(
    client: TestClient, published_written: dict[str, Any]
) -> None:
    owner, other = _learner(client), _learner(client)
    a = _start(client, owner, published_written["chapter"])
    first = _upload(client, owner, a["id"], _png(seed=1))
    assert first.status_code == 201 and not first.json()["duplicate"]
    again = _upload(client, owner, a["id"], _png(seed=1))
    assert again.json()["duplicate"] and again.json()["pages"][0]["id"] == first.json()["pages"][0]["id"]
    bad = _upload(client, owner, a["id"], b"not an image")
    assert bad.status_code == 422 and "JPEG, PNG or PDF" in bad.json()["detail"]
    page_id = first.json()["pages"][0]["id"]
    got = client.get(f"/v1/written-attempts/{a['id']}/pages/{page_id}", headers=owner.headers)
    assert got.status_code == 200 and got.headers["cache-control"] == "private, no-store"
    assert got.headers["content-type"] == "image/png" and got.content.startswith(PNG_SIGNATURE)  # the preview
    assert client.get(f"/v1/written-attempts/{a['id']}/pages/{page_id}", headers=other.headers).status_code == 404
    assert _upload(client, other, a["id"], _png(seed=2)).status_code == 404


def test_mapping_uses_revision_concurrency(client: TestClient, published_written: dict[str, Any]) -> None:
    who = _learner(client)
    a = _start(client, who, published_written["chapter"])
    page = _upload(client, who, a["id"], _png(seed=3)).json()["pages"][0]["id"]
    ok = _map(client, who, a, {"1:a": {"pages": [page]}})
    assert ok.status_code == 200 and ok.json()["manifest_revision"] == 1
    stale = _map(client, who, a, {"1:b": {"pages": [page]}}, revision=0)
    assert stale.status_code == 409 and stale.json()["current"]["revision"] == 1
    invalid = _map(client, who, ok.json(), {"1:a": {"pages": [page], "unanswered": True}, "9:z": {"pages": []}})
    assert invalid.status_code == 422 and len(invalid.json()["errors"]) == 2


# ------------------------------------------------------------------ seal
def test_seal_requires_completeness_and_returns_one_receipt(
    client: TestClient, published_written: dict[str, Any]
) -> None:
    who = _learner(client)
    a = _start(client, who, published_written["chapter"], writing_minutes=20)
    p1 = _upload(client, who, a["id"], _png(seed=4)).json()["pages"][0]["id"]
    m = _map(client, who, a, {"1:a": {"pages": [p1]}}).json()
    incomplete = _seal(client, who, a["id"], m["manifest_revision"])
    assert incomplete.status_code == 422 and incomplete.json()["missing"] == ["1:b"]
    m = _map(client, who, m, {"1:a": {"pages": [p1]}, "1:b": {"unanswered": True}}).json()
    key = uuid.uuid4().hex
    sealed = _seal(client, who, a["id"], m["manifest_revision"], key)
    assert sealed.status_code == 200 and not sealed.json()["replay"]
    receipt = sealed.json()["receipt"]
    assert receipt["answered_slots"] == 1 and receipt["unanswered_slots"] == 1
    replay = _seal(client, who, a["id"], m["manifest_revision"], key)
    assert replay.json()["receipt"] == receipt and replay.json()["replay"]
    assert _seal(client, who, a["id"], m["manifest_revision"] + 5, key).status_code == 409  # same key, changed payload
    assert _seal(client, who, a["id"], m["manifest_revision"]).status_code == 409  # already sealed
    assert _upload(client, who, a["id"], _png(seed=5)).status_code == 409  # no post-seal edits
    assert _map(client, who, m, {"1:a": {"unanswered": True}, "1:b": {"unanswered": True}}).status_code == 409
    # The exact retry still returns the receipt after U.
    _shift(a["id"], cutoff_offset_s=-60)
    assert _seal(client, who, a["id"], m["manifest_revision"], key).json()["receipt"] == receipt


def test_nothing_is_admitted_after_the_upload_cutoff(client: TestClient, published_written: dict[str, Any]) -> None:
    who = _learner(client)
    a = _start(client, who, published_written["chapter"], writing_minutes=20)
    p1 = _upload(client, who, a["id"], _png(seed=6)).json()["pages"][0]["id"]
    m = _map(client, who, a, {"1:a": {"pages": [p1]}, "1:b": {"pages": [p1]}}).json()  # one page may cover two parts
    _shift(a["id"], cutoff_offset_s=-0.001)
    late = _seal(client, who, a["id"], m["manifest_revision"])
    assert late.status_code == 409 and late.json()["attempt_status"] == "expired"
    resumed = client.get(f"/v1/written-attempts/{a['id']}", headers=who.headers).json()
    assert resumed["status"] == "expired" and resumed["receipt"] is None and len(resumed["pages"]) == 1  # honest
    assert _upload(client, who, a["id"], _png(seed=7)).status_code == 409


def test_seal_detects_tampered_evidence(client: TestClient, published_written: dict[str, Any]) -> None:
    from portal_api.modules.written import storage

    who = _learner(client)
    a = _start(client, who, published_written["chapter"])
    up = _upload(client, who, a["id"], _png(seed=8)).json()["pages"][0]
    m = _map(client, who, a, {"1:a": {"pages": [up["id"]]}, "1:b": {"unanswered": True}}).json()
    path = storage.get_store().root / f"{a['id']}/{up['file_id']}/original"
    path.write_bytes(path.read_bytes() + b"tampered")
    r = _seal(client, who, a["id"], m["manifest_revision"])
    assert r.status_code == 409 and "integrity check" in r.json()["detail"]
