/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Book */
        get: operations["book_v1_books__book_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Grades → subjects → books (Class XI and XII separate) */
        get: operations["catalogue_v1_catalogue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chapters/{chapter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chapter */
        get: operations["chapter_v1_chapters__chapter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/grades/{grade}/subjects/{subject}/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The book for one grade+subject */
        get: operations["book_for_v1_grades__grade__subjects__subject__book_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runtime-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime Config */
        get: operations["runtime_config_v1_runtime_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search chapters and topics; every hit is labelled with its grade */
        get: operations["search_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BookOut */
        BookOut: {
            /** Authority */
            authority: string | null;
            breadcrumb: components["schemas"]["Breadcrumb"];
            /** Chapters */
            chapters: components["schemas"]["ChapterSummary"][];
            /** Completeness */
            completeness: string;
            /** Edition */
            edition: string | null;
            /** Missing Pages */
            missing_pages: string[];
        };
        /** BookSummary */
        BookSummary: {
            /** Chapter Count */
            chapter_count: number;
            /** Chapter Label */
            chapter_label: string;
            /** Completeness */
            completeness: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string | null;
        };
        /** Breadcrumb */
        Breadcrumb: {
            /**
             * Book Id
             * Format: uuid
             */
            book_id: string;
            /** Book Title */
            book_title: string | null;
            /** Chapter Label */
            chapter_label: string;
            grade: components["schemas"]["GradeOut"];
            /** Source Id */
            source_id: string;
            subject: components["schemas"]["SubjectOut"];
        };
        /** CatalogueOut */
        CatalogueOut: {
            /** Grades */
            grades: components["schemas"]["GradeCatalogue"][];
            /** Region */
            region: string;
            /** Scope Decision */
            scope_decision: string;
        };
        /** ChapterOut */
        ChapterOut: {
            /** Assessment Counts */
            assessment_counts: {
                [key: string]: number;
            };
            breadcrumb: components["schemas"]["Breadcrumb"];
            /** Content State */
            content_state: string;
            /** Contents Number */
            contents_number: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key Terms */
            key_terms: string[];
            /** Main Concept */
            main_concept: string | null;
            /** Next Chapter Id */
            next_chapter_id: string | null;
            /** Number */
            number: number;
            /** Previous Chapter Id */
            previous_chapter_id: string | null;
            /** Slo Codes */
            slo_codes: string | null;
            source: components["schemas"]["SourceRef"];
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Topics */
            topics: components["schemas"]["TopicNode"][];
            /** Visual Count */
            visual_count: number;
        };
        /** ChapterSummary */
        ChapterSummary: {
            /** Assessment Counts */
            assessment_counts: {
                [key: string]: number;
            };
            /** Content State */
            content_state: string;
            /** Contents Number */
            contents_number: number | null;
            /** Display Order */
            display_order: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /** Pdf End */
            pdf_end: number | null;
            /** Pdf Start */
            pdf_start: number | null;
            /** Printed End */
            printed_end: number | null;
            /** Printed Start */
            printed_start: number | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Topic Count */
            topic_count: number;
            /** Visual Count */
            visual_count: number;
        };
        /** GradeCatalogue */
        GradeCatalogue: {
            grade: components["schemas"]["GradeOut"];
            /** Subjects */
            subjects: components["schemas"]["SubjectInGrade"][];
        };
        /** GradeOut */
        GradeOut: {
            /** Code */
            code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Number */
            number: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RuntimeConfig */
        RuntimeConfig: {
            /** Active Grades */
            active_grades: number[];
            /** Active Subjects */
            active_subjects: string[];
            /** Api Origin */
            api_origin: string;
            /** Build Id */
            build_id: string;
            /** Media Origin */
            media_origin: string;
            /** Region */
            region: string;
            /** Role */
            role: string;
            /** Scope Decision */
            scope_decision: string;
        };
        /** SearchHit */
        SearchHit: {
            /**
             * Chapter Id
             * Format: uuid
             */
            chapter_id: string;
            /** Chapter Title */
            chapter_title: string;
            /** Grade */
            grade: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Number */
            number: string | null;
            /** Pdf Page */
            pdf_page: number | null;
            /** Score */
            score: number;
            /** Subject Code */
            subject_code: string;
            /** Subject Name */
            subject_name: string;
            /** Title */
            title: string;
        };
        /** SearchOut */
        SearchOut: {
            /** Grade */
            grade: number | null;
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
            /** Query */
            query: string;
            /** Subject */
            subject: string | null;
        };
        /**
         * SourceRef
         * @description Where a chapter/topic lives in the owner's original file (PDF pages are 1-based file indices).
         */
        SourceRef: {
            /** File */
            file: string;
            /** Page Rule */
            page_rule: string | null;
            /** Pdf End */
            pdf_end: number | null;
            /** Pdf Start */
            pdf_start: number | null;
            /** Printed End */
            printed_end: number | null;
            /** Printed Start */
            printed_start: number | null;
            /** Sha256 */
            sha256: string;
            /** Source Id */
            source_id: string;
        };
        /** SubjectInGrade */
        SubjectInGrade: {
            /** Books */
            books: components["schemas"]["BookSummary"][];
            subject: components["schemas"]["SubjectOut"];
        };
        /** SubjectOut */
        SubjectOut: {
            /** Aliases */
            aliases: string[];
            /** Code */
            code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** TopicNode */
        TopicNode: {
            /** Children */
            children: components["schemas"]["TopicNode"][];
            /** Depth */
            depth: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: string | null;
            /** Pdf Page */
            pdf_page: number | null;
            /** Points */
            points: string[];
            /** Title */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    book_v1_books__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalogue_v1_catalogue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogueOut"];
                };
            };
        };
    };
    chapter_v1_chapters__chapter_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book_for_v1_grades__grade__subjects__subject__book_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grade: number;
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runtime_config_v1_runtime_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfig"];
                };
            };
        };
    };
    search_v1_search_get: {
        parameters: {
            query: {
                q: string;
                grade?: number | null;
                subject?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
