/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/admin/role-grants/{grant_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Role */
        post: operations["revoke_role_v1_admin_role_grants__grant_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{user_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_v1_admin_users__user_id__roles_get"];
        put?: never;
        /** Grant Role */
        post: operations["grant_role_v1_admin_users__user_id__roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Book */
        get: operations["book_v1_books__book_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Grades → subjects → books (Class XI and XII separate) */
        get: operations["catalogue_v1_catalogue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chapters/{chapter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chapter */
        get: operations["chapter_v1_chapters__chapter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chapters/{chapter_id}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Published, live lessons for a chapter (academically approved; never drafts) */
        get: operations["chapter_lessons_v1_chapters__chapter_id__lessons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/grades/{grade}/subjects/{subject}/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The book for one grade+subject */
        get: operations["book_for_v1_grades__grade__subjects__subject__book_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in account, its roles, profile and consents */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a versioned document */
        post: operations["accept_consent_v1_me_consents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/consents/{document}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Withdraw an optional consent */
        delete: operations["withdraw_consent_v1_me_consents__document__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save onboarding/learning preferences */
        put: operations["put_profile_v1_me_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Sign out (revoke the current session) */
        delete: operations["sign_out_v1_me_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_v1_me_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/sessions/revoke-others": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Other Sessions */
        post: operations["revoke_other_sessions_v1_me_sessions_revoke_others_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Session */
        delete: operations["revoke_session_v1_me_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runtime-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime Config */
        get: operations["runtime_config_v1_runtime_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search chapters and topics; every hit is labelled with its grade */
        get: operations["search_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Exchange a verified identity-provider access token for a revocable application session.
         */
        post: operations["create_session_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/block-registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Block types, schema version and renderer requirements (§5.4) */
        get: operations["block_registry_v1_studio_block_registry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create */
        post: operations["create_v1_studio_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Item Detail */
        get: operations["item_detail_v1_studio_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/items/{item_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign */
        post: operations["assign_v1_studio_items__item_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/items/{item_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Autosave with a revision check (P06.S1.T3) */
        put: operations["save_draft_v1_studio_items__item_id__draft_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/items/{item_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit history for one item */
        get: operations["item_history_v1_studio_items__item_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/items/{item_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: operations["publish_v1_studio_items__item_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/items/{item_id}/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quarantine */
        post: operations["quarantine_v1_studio_items__item_id__quarantine_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/items/{item_id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release */
        post: operations["release_v1_studio_items__item_id__release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/items/{item_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire */
        post: operations["retire_v1_studio_items__item_id__retire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/items/{item_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_v1_studio_items__item_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/items/{item_id}/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise */
        post: operations["revise_v1_studio_items__item_id__revise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/items/{item_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit */
        post: operations["submit_v1_studio_items__item_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/items/{item_id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw */
        post: operations["withdraw_v1_studio_items__item_id__withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Editorial work queue (P06.S1.T2) */
        get: operations["queue_v1_studio_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source documents and their publication-rights state */
        get: operations["sources_v1_studio_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/sources/{source_id}/publication-rights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Owner's publication-rights decision for material derived from a source (audited, MFA) */
        put: operations["set_rights_v1_studio_sources__source_id__publication_rights_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/studio/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dry-run validation for the editor (writes nothing) */
        post: operations["validate_v1_studio_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Actions
         * @description What the caller may do now. Advisory for the UI; the server re-checks every action.
         */
        Actions: {
            /** Claim */
            claim: boolean;
            /** Edit */
            edit: boolean;
            /** Publish */
            publish: boolean;
            /** Quarantine */
            quarantine: boolean;
            /** Release */
            release: boolean;
            /** Retire */
            retire: boolean;
            /** Review */
            review: boolean;
            /** Revise */
            revise: boolean;
            /** Submit */
            submit: boolean;
            /** Withdraw */
            withdraw: boolean;
        };
        /** AssignIn */
        AssignIn: {
            /** Reviewer Id */
            reviewer_id: string | null;
        };
        /** BookOut */
        BookOut: {
            /** Authority */
            authority: string | null;
            breadcrumb: components["schemas"]["Breadcrumb"];
            /** Chapters */
            chapters: components["schemas"]["ChapterSummary"][];
            /** Completeness */
            completeness: string;
            /** Edition */
            edition: string | null;
            /** Missing Pages */
            missing_pages: string[];
        };
        /** BookSummary */
        BookSummary: {
            /** Chapter Count */
            chapter_count: number;
            /** Chapter Label */
            chapter_label: string;
            /** Completeness */
            completeness: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string | null;
        };
        /** Breadcrumb */
        Breadcrumb: {
            /**
             * Book Id
             * Format: uuid
             */
            book_id: string;
            /** Book Title */
            book_title: string | null;
            /** Chapter Label */
            chapter_label: string;
            grade: components["schemas"]["GradeOut"];
            /** Source Id */
            source_id: string;
            subject: components["schemas"]["SubjectOut"];
        };
        /** CatalogueOut */
        CatalogueOut: {
            /** Grades */
            grades: components["schemas"]["GradeCatalogue"][];
            /** Region */
            region: string;
            /** Scope Decision */
            scope_decision: string;
        };
        /** ChangeReasonIn */
        ChangeReasonIn: {
            /** Reason */
            reason: string;
        };
        /** ChapterOut */
        ChapterOut: {
            /** Assessment Counts */
            assessment_counts: {
                [key: string]: number;
            };
            breadcrumb: components["schemas"]["Breadcrumb"];
            /** Content State */
            content_state: string;
            /** Contents Number */
            contents_number: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key Terms */
            key_terms: string[];
            /** Main Concept */
            main_concept: string | null;
            /** Next Chapter Id */
            next_chapter_id: string | null;
            /** Number */
            number: number;
            /** Previous Chapter Id */
            previous_chapter_id: string | null;
            /** Slo Codes */
            slo_codes: string | null;
            source: components["schemas"]["SourceRef"];
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Topics */
            topics: components["schemas"]["TopicNode"][];
            /** Visual Count */
            visual_count: number;
        };
        /** ChapterSummary */
        ChapterSummary: {
            /** Assessment Counts */
            assessment_counts: {
                [key: string]: number;
            };
            /** Content State */
            content_state: string;
            /** Contents Number */
            contents_number: number | null;
            /** Display Order */
            display_order: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /** Pdf End */
            pdf_end: number | null;
            /** Pdf Start */
            pdf_start: number | null;
            /** Printed End */
            printed_end: number | null;
            /** Printed Start */
            printed_start: number | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Topic Count */
            topic_count: number;
            /** Visual Count */
            visual_count: number;
        };
        /** ConsentIn */
        ConsentIn: {
            /**
             * Document
             * @enum {string}
             */
            document: "terms" | "privacy" | "marketing_messages";
            /** Version */
            version: string;
        };
        /** ConsentOut */
        ConsentOut: {
            /**
             * Accepted At
             * Format: date-time
             */
            accepted_at: string;
            /** Document */
            document: string;
            /** Version */
            version: string;
            /** Withdrawn At */
            withdrawn_at: string | null;
        };
        /** DraftIn */
        DraftIn: {
            /** Body */
            body: {
                [key: string]: unknown;
            };
            /**
             * Revision
             * @description The revision this edit started from; a stale value returns 409.
             */
            revision: number;
            /** Source Refs */
            source_refs?: {
                [key: string]: unknown;
            }[];
            /** Title */
            title?: string | null;
        };
        /** GradeCatalogue */
        GradeCatalogue: {
            grade: components["schemas"]["GradeOut"];
            /** Subjects */
            subjects: components["schemas"]["SubjectInGrade"][];
        };
        /** GradeOut */
        GradeOut: {
            /** Code */
            code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Number */
            number: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryEvent */
        HistoryEvent: {
            /** Action */
            action: string;
            /** Actor */
            actor: string | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** ItemCreateIn */
        ItemCreateIn: {
            /**
             * Chapter Id
             * Format: uuid
             */
            chapter_id: string;
            /** Title */
            title: string;
            /** Topic Id */
            topic_id?: string | null;
        };
        /** ItemDetail */
        ItemDetail: {
            actions: components["schemas"]["Actions"];
            /** Assigned Reviewer */
            assigned_reviewer: string | null;
            /** Assigned Reviewer Id */
            assigned_reviewer_id: string | null;
            /**
             * Availability
             * @enum {string}
             */
            availability: "unpublished" | "live" | "quarantined" | "retired";
            /** Availability Reason */
            availability_reason: string | null;
            /**
             * Blockers
             * @description Why the next step can't happen yet (e.g. rights unverified).
             */
            blockers: string[];
            /**
             * Chapter Id
             * Format: uuid
             */
            chapter_id: string;
            /** Chapter Pdf End */
            chapter_pdf_end: number | null;
            /** Chapter Pdf Start */
            chapter_pdf_start: number | null;
            /** Chapter Title */
            chapter_title: string;
            /** Created By */
            created_by: string | null;
            /** Grade Number */
            grade_number: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Open Feedback
             * @description Change requests on the working version not yet addressed.
             */
            open_feedback: number;
            published: components["schemas"]["VersionOut"] | null;
            /** Published Version */
            published_version: number | null;
            source: components["schemas"]["SourceOut"];
            /**
             * State
             * @enum {string}
             */
            state: "draft" | "submitted" | "changes_requested" | "approved" | "published";
            /** Subject Code */
            subject_code: string;
            /** Title */
            title: string;
            /** Topic Id */
            topic_id: string | null;
            /** Topic Title */
            topic_title: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            working: components["schemas"]["VersionOut"] | null;
            /** Working Version */
            working_version: number | null;
        };
        /** ItemSummary */
        ItemSummary: {
            /** Assigned Reviewer */
            assigned_reviewer: string | null;
            /** Assigned Reviewer Id */
            assigned_reviewer_id: string | null;
            /**
             * Availability
             * @enum {string}
             */
            availability: "unpublished" | "live" | "quarantined" | "retired";
            /**
             * Chapter Id
             * Format: uuid
             */
            chapter_id: string;
            /** Chapter Title */
            chapter_title: string;
            /** Created By */
            created_by: string | null;
            /** Grade Number */
            grade_number: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Open Feedback
             * @description Change requests on the working version not yet addressed.
             */
            open_feedback: number;
            /** Published Version */
            published_version: number | null;
            /**
             * State
             * @enum {string}
             */
            state: "draft" | "submitted" | "changes_requested" | "approved" | "published";
            /** Subject Code */
            subject_code: string;
            /** Title */
            title: string;
            /** Topic Id */
            topic_id: string | null;
            /** Topic Title */
            topic_title: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Working Version */
            working_version: number | null;
        };
        /** LessonOut */
        LessonOut: {
            /** Block Types */
            block_types: string[];
            /** Body */
            body: {
                [key: string]: unknown;
            };
            /** Content Schema Version */
            content_schema_version: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Source Refs */
            source_refs: {
                [key: string]: unknown;
            }[];
            /** Title */
            title: string;
            /** Topic Id */
            topic_id: string | null;
            /** Version */
            version: number;
        };
        /** MeOut */
        MeOut: {
            /** Consents */
            consents: components["schemas"]["ConsentOut"][];
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mfa Session */
            mfa_session: boolean;
            profile: components["schemas"]["ProfileOut"] | null;
            /** Roles */
            roles: components["schemas"]["Role"][];
            /** Status */
            status: string;
        };
        /**
         * ProfileIn
         * @description Onboarding answers (P04.S3.T1). Everything can be corrected later; no identity documents are collected.
         */
        ProfileIn: {
            /** Daily Minutes */
            daily_minutes?: number | null;
            /**
             * Explanation Language
             * @default en
             * @enum {string}
             */
            explanation_language: "en" | "ur" | "roman_ur";
            /** Grade */
            grade?: (11 | 12) | null;
            /** Stream */
            stream?: ("pre_medical" | "pre_engineering" | "ics") | null;
            /** Subjects */
            subjects?: ("biology" | "chemistry" | "physics" | "computer_science" | "mathematics")[];
            /** Target Exams */
            target_exams?: ("mdcat" | "ecat")[];
            /** Target Year */
            target_year?: number | null;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Daily Minutes */
            daily_minutes?: number | null;
            /**
             * Explanation Language
             * @default en
             * @enum {string}
             */
            explanation_language: "en" | "ur" | "roman_ur";
            /** Grade */
            grade?: (11 | 12) | null;
            /** Stream */
            stream?: ("pre_medical" | "pre_engineering" | "ics") | null;
            /** Subjects */
            subjects?: ("biology" | "chemistry" | "physics" | "computer_science" | "mathematics")[];
            /** Target Exams */
            target_exams?: ("mdcat" | "ecat")[];
            /** Target Year */
            target_year?: number | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ReviewIn */
        ReviewIn: {
            /** Comment */
            comment: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "request_changes";
        };
        /** ReviewOut */
        ReviewOut: {
            /** Comment */
            comment: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "request_changes";
            /** Reviewer */
            reviewer: string | null;
        };
        /** RevokeIn */
        RevokeIn: {
            /** Reason */
            reason: string;
        };
        /** RightsIn */
        RightsIn: {
            /**
             * Evidence
             * @description Where the owner's decision is documented.
             */
            evidence: string;
            /**
             * Rights
             * @enum {string}
             */
            rights: "UNVERIFIED" | "CONFIRMED" | "DENIED";
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "student" | "content_author" | "subject_reviewer" | "academic_adjudicator" | "publisher" | "support" | "finance" | "platform_operator" | "owner_admin";
        /** RoleGrantIn */
        RoleGrantIn: {
            /** Reason */
            reason: string;
            role: components["schemas"]["Role"];
            /** Scope */
            scope?: {
                [key: string]: unknown;
            };
        };
        /** RoleGrantOut */
        RoleGrantOut: {
            /**
             * Granted At
             * Format: date-time
             */
            granted_at: string;
            /** Granted By */
            granted_by: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason: string;
            /** Revoke Reason */
            revoke_reason: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /** Role */
            role: string;
            /** Scope */
            scope: {
                [key: string]: unknown;
            };
        };
        /** RuntimeConfig */
        RuntimeConfig: {
            /** Active Grades */
            active_grades: number[];
            /** Active Subjects */
            active_subjects: string[];
            /** Api Origin */
            api_origin: string;
            /** Build Id */
            build_id: string;
            /** Media Origin */
            media_origin: string;
            /** Region */
            region: string;
            /** Role */
            role: string;
            /** Scope Decision */
            scope_decision: string;
            /** Sign In Methods */
            sign_in_methods: string[];
        };
        /** SearchHit */
        SearchHit: {
            /**
             * Chapter Id
             * Format: uuid
             */
            chapter_id: string;
            /** Chapter Title */
            chapter_title: string;
            /** Grade */
            grade: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Number */
            number: string | null;
            /** Pdf Page */
            pdf_page: number | null;
            /** Score */
            score: number;
            /** Subject Code */
            subject_code: string;
            /** Subject Name */
            subject_name: string;
            /** Title */
            title: string;
        };
        /** SearchOut */
        SearchOut: {
            /** Grade */
            grade: number | null;
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
            /** Query */
            query: string;
            /** Subject */
            subject: string | null;
        };
        /** SessionCreateIn */
        SessionCreateIn: {
            /** Device Label */
            device_label?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "web" | "native";
        };
        /** SessionCreatedOut */
        SessionCreatedOut: {
            session: components["schemas"]["SessionOut"];
            /** Session Token */
            session_token: string;
        };
        /** SessionOut */
        SessionOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Current
             * @default false
             */
            current: boolean;
            /** Device Label */
            device_label: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Mfa */
            mfa: boolean;
            /** User Agent */
            user_agent: string | null;
        };
        /** SourceOut */
        SourceOut: {
            /** Grade Number */
            grade_number: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Missing Pages */
            missing_pages: unknown[];
            /** Pdf Pages */
            pdf_pages: number;
            /**
             * Publication Rights
             * @enum {string}
             */
            publication_rights: "UNVERIFIED" | "CONFIRMED" | "DENIED";
            /** Publication Rights Evidence */
            publication_rights_evidence: string | null;
            /** Publication Rights Set At */
            publication_rights_set_at: string | null;
            /** Source Id */
            source_id: string;
            /** Subject Code */
            subject_code: string;
            /** Title */
            title: string | null;
        };
        /**
         * SourceRef
         * @description Where a chapter/topic lives in the owner's original file (PDF pages are 1-based file indices).
         */
        SourceRef: {
            /** File */
            file: string;
            /** Page Rule */
            page_rule: string | null;
            /** Pdf End */
            pdf_end: number | null;
            /** Pdf Start */
            pdf_start: number | null;
            /** Printed End */
            printed_end: number | null;
            /** Printed Start */
            printed_start: number | null;
            /** Sha256 */
            sha256: string;
            /** Source Id */
            source_id: string;
        };
        /** SubjectInGrade */
        SubjectInGrade: {
            /** Books */
            books: components["schemas"]["BookSummary"][];
            subject: components["schemas"]["SubjectOut"];
        };
        /** SubjectOut */
        SubjectOut: {
            /** Aliases */
            aliases: string[];
            /** Code */
            code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** SubmitIn */
        SubmitIn: {
            /** Note */
            note?: string | null;
        };
        /** TopicNode */
        TopicNode: {
            /** Children */
            children: components["schemas"]["TopicNode"][];
            /** Depth */
            depth: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: string | null;
            /** Pdf Page */
            pdf_page: number | null;
            /** Points */
            points: string[];
            /** Title */
            title: string;
        };
        /** ValidateIn */
        ValidateIn: {
            /** Body */
            body: {
                [key: string]: unknown;
            };
            /**
             * Chapter Id
             * Format: uuid
             */
            chapter_id: string;
            /**
             * For Publication
             * @default false
             */
            for_publication: boolean;
            /** Source Refs */
            source_refs?: {
                [key: string]: unknown;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationOut */
        ValidationOut: {
            /** Block Types */
            block_types: string[];
            /** Errors */
            errors: string[];
            /** Ok */
            ok: boolean;
            /** Warnings */
            warnings: string[];
        };
        /** VersionOut */
        VersionOut: {
            /** Approved At */
            approved_at: string | null;
            /** Approved By */
            approved_by: string | null;
            /** Block Types */
            block_types: string[];
            /** Body */
            body: {
                [key: string]: unknown;
            };
            /** Change Reason */
            change_reason: string | null;
            /** Content Schema Version */
            content_schema_version: number;
            /** Contributors */
            contributors: string[];
            /** Created By */
            created_by: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /** Published At */
            published_at: string | null;
            /** Published By */
            published_by: string | null;
            /** Reviews */
            reviews: components["schemas"]["ReviewOut"][];
            /** Revision */
            revision: number;
            /** Source Refs */
            source_refs: {
                [key: string]: unknown;
            }[];
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "submitted" | "changes_requested" | "approved" | "published" | "superseded";
            /** Submitted At */
            submitted_at: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    revoke_role_v1_admin_role_grants__grant_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleGrantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_v1_admin_users__user_id__roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleGrantOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_role_v1_admin_users__user_id__roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleGrantIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleGrantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book_v1_books__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalogue_v1_catalogue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogueOut"];
                };
            };
        };
    };
    chapter_v1_chapters__chapter_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chapter_lessons_v1_chapters__chapter_id__lessons_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book_for_v1_grades__grade__subjects__subject__book_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grade: number;
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    accept_consent_v1_me_consents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_consent_v1_me_consents__document__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_profile_v1_me_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_out_v1_me_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_sessions_v1_me_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
        };
    };
    revoke_other_sessions_v1_me_sessions_revoke_others_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_session_v1_me_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runtime_config_v1_runtime_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfig"];
                };
            };
        };
    };
    search_v1_search_get: {
        parameters: {
            query: {
                q: string;
                grade?: number | null;
                subject?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreatedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    block_registry_v1_studio_block_registry_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_v1_studio_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_detail_v1_studio_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_v1_studio_items__item_id__assign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_draft_v1_studio_items__item_id__draft_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_history_v1_studio_items__item_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_v1_studio_items__item_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quarantine_v1_studio_items__item_id__quarantine_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeReasonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_v1_studio_items__item_id__release_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeReasonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_v1_studio_items__item_id__retire_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeReasonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_v1_studio_items__item_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_v1_studio_items__item_id__revise_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeReasonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_v1_studio_items__item_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_v1_studio_items__item_id__withdraw_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_v1_studio_queue_get: {
        parameters: {
            query?: {
                state?: string | null;
                availability?: string | null;
                grade?: number | null;
                subject?: string | null;
                mine?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_v1_studio_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
        };
    };
    set_rights_v1_studio_sources__source_id__publication_rights_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RightsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_v1_studio_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
