"""written evidence revisions and learner actions (W04.S3.T2, W06.S2.T4)

Revision ID: 20fefbdf84f1
Revises: 2365ef539356
Create Date: 2026-10-08 14:06:50.297390

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20fefbdf84f1"
down_revision: str | Sequence[str] | None = "2365ef539356"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "written_evidence_revision",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("prior_page_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prior_hashes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("post_cutoff", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("classification", sa.String(length=14), nullable=True),
        sa.Column("class_reason", sa.Text(), nullable=True),
        sa.Column("classified_by", sa.UUID(), nullable=True),
        sa.Column("classified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "classification is null or classification in ('READABILITY','NEW_CONTENT','INDETERMINATE')",
            name="written_revision_class",
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["attempt_id"], ["written_attempt.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["case_id"], ["written_review_case.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["classified_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["file_id"], ["written_file.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_written_evidence_revision_attempt_id"), "written_evidence_revision", ["attempt_id"], unique=False
    )
    op.alter_column("written_score_version", "assessor_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
    for table, name in (("written_file", "written_file_status"), ("written_page", "written_page_status")):
        op.drop_constraint(name, table, type_="check")
        op.create_check_constraint(name, table, "status in ('uploaded','withdrawn','revision')")


def downgrade() -> None:
    """Downgrade schema. Refused once rescans or system decisions exist (they can't be represented before this)."""
    bind = op.get_bind()
    if (
        bind.execute(sa.text("select 1 from written_evidence_revision limit 1")).scalar()
        or bind.execute(sa.text("select 1 from written_score_version where assessor_id is null limit 1")).scalar()
    ):
        raise RuntimeError("rescans or system decisions exist; downgrading would lose evidence history")
    for table, name in (("written_file", "written_file_status"), ("written_page", "written_page_status")):
        op.drop_constraint(name, table, type_="check")
        op.create_check_constraint(name, table, "status in ('uploaded','withdrawn')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("written_score_version", "assessor_id", existing_type=sa.UUID(), nullable=False)
    op.drop_index(op.f("ix_written_evidence_revision_attempt_id"), table_name="written_evidence_revision")
    op.drop_table("written_evidence_revision")
    # ### end Alembic commands ###
