"""rescan retry keys, durable learner obligations, evidence provenance (PR #31 review RS31-01/02/03, section 4)

Revision ID: 74ef206e3de6
Revises: 20fefbdf84f1
Create Date: 2026-10-08 15:05:44.720797

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "74ef206e3de6"
down_revision: str | Sequence[str] | None = "20fefbdf84f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "written_learner_obligation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.String(length=30), nullable=True),
        sa.CheckConstraint("status in ('open','resolved')", name="written_obligation_status"),
        sa.ForeignKeyConstraint(["attempt_id"], ["written_attempt.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_written_learner_obligation_attempt_id"), "written_learner_obligation", ["attempt_id"], unique=False
    )
    op.create_index(
        "uq_written_obligation_open",
        "written_learner_obligation",
        ["attempt_id", "position"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.add_column("written_evidence_revision", sa.Column("idempotency_key", sa.String(length=80), nullable=True))
    op.add_column("written_evidence_revision", sa.Column("request_hash", sa.String(length=64), nullable=True))
    # Rescans admitted before retry keys existed get a legacy key derived from their id (they can't be replayed).
    op.execute(
        "update written_evidence_revision set idempotency_key = 'legacy-' || id::text, "
        "request_hash = encode(sha256(convert_to(id::text, 'UTF8')), 'hex') where idempotency_key is null"
    )
    op.alter_column("written_evidence_revision", "idempotency_key", nullable=False)
    op.alter_column("written_evidence_revision", "request_hash", nullable=False)
    op.create_unique_constraint(
        "uq_written_revision_key", "written_evidence_revision", ["attempt_id", "idempotency_key"]
    )
    op.add_column(
        "written_score_version",
        sa.Column("evidence_revisions", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
    )
    # ### end Alembic commands ###
    # Open learner requests in current results become durable obligations, keeping their first deadline (RS31-02).
    op.execute(
        """
        insert into written_learner_obligation (id, attempt_id, position, action, requested_at, deadline, status)
        select gen_random_uuid(), v.attempt_id, q.key::smallint, q.value->>'learner_action',
               v.created_at, (q.value->>'action_deadline')::timestamptz, 'open'
        from written_score_version v
        join (select attempt_id, max(version) as version from written_score_version where released group by attempt_id) last
          on last.attempt_id = v.attempt_id and last.version = v.version
        cross join lateral jsonb_each(v.question_status) q
        where q.value->>'status' = 'pending' and q.value ? 'learner_action' and q.value ? 'action_deadline'
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("written_score_version", "evidence_revisions")
    op.drop_constraint("uq_written_revision_key", "written_evidence_revision", type_="unique")
    op.drop_column("written_evidence_revision", "request_hash")
    op.drop_column("written_evidence_revision", "idempotency_key")
    op.drop_index(
        "uq_written_obligation_open",
        table_name="written_learner_obligation",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index(op.f("ix_written_learner_obligation_attempt_id"), table_name="written_learner_obligation")
    op.drop_table("written_learner_obligation")
    # ### end Alembic commands ###
