"""written review cases and score versions

Revision ID: b4c149c0d98e
Revises: db69629fbe8e
Create Date: 2026-10-07 07:24:08.214808

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b4c149c0d98e"
down_revision: str | Sequence[str] | None = "db69629fbe8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "written_review_case",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("case_kind", sa.String(length=10), nullable=False),
        sa.Column("opened_seq", sa.SmallInteger(), nullable=False),
        sa.Column("grade_number", sa.SmallInteger(), nullable=False),
        sa.Column("subject_code", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("lease_holder", sa.UUID(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.CheckConstraint("case_kind in ('initial','recheck')", name="written_case_kind"),
        sa.CheckConstraint("status in ('queued','released')", name="written_case_status"),
        sa.ForeignKeyConstraint(["attempt_id"], ["written_attempt.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["lease_holder"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", "case_kind", "opened_seq", name="uq_written_case"),
    )
    op.create_index(op.f("ix_written_review_case_attempt_id"), "written_review_case", ["attempt_id"], unique=False)
    op.create_table(
        "written_score_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.SmallInteger(), nullable=False),
        sa.Column("prior_version_id", sa.UUID(), nullable=True),
        sa.Column("decision_method", sa.String(length=10), nullable=False),
        sa.Column("case_kind", sa.String(length=10), nullable=False),
        sa.Column("assessor_id", sa.UUID(), nullable=False),
        sa.Column("receipt_id", sa.UUID(), nullable=False),
        sa.Column("rubric_version_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("awards", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("question_units", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total_units", sa.Integer(), nullable=False),
        sa.Column("max_units", sa.Integer(), nullable=False),
        sa.Column("released", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["assessor_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["attempt_id"], ["written_attempt.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["case_id"], ["written_review_case.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["prior_version_id"], ["written_score_version.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["receipt_id"], ["written_receipt.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", "version"),
    )
    op.create_index(op.f("ix_written_score_version_attempt_id"), "written_score_version", ["attempt_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_written_score_version_attempt_id"), table_name="written_score_version")
    op.drop_table("written_score_version")
    op.drop_index(op.f("ix_written_review_case_attempt_id"), table_name="written_review_case")
    op.drop_table("written_review_case")
    # ### end Alembic commands ###
