"""support tickets and messages

Revision ID: 24d95c7ec9ae
Revises: eea7fd88f3f1
Create Date: 2026-10-07 08:33:17.633800

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "24d95c7ec9ae"
down_revision: str | Sequence[str] | None = "eea7fd88f3f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "support_ticket",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reference", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_item_id", sa.UUID(), nullable=True),
        sa.Column("content_version_id", sa.UUID(), nullable=True),
        sa.Column("grade_number", sa.SmallInteger(), nullable=True),
        sa.Column("subject_code", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "category in ('account', 'access', 'technical', 'academic_report', 'other')", name="support_ticket_category"
        ),
        sa.CheckConstraint(
            "status in ('open', 'in_progress', 'waiting_learner', 'resolved')", name="support_ticket_status"
        ),
        sa.ForeignKeyConstraint(["content_item_id"], ["content_item.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["content_version_id"], ["content_version.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_support_ticket_user_id"), "support_ticket", ["user_id"], unique=False)
    op.create_table(
        "support_message",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("from_staff", sa.Boolean(), nullable=False),
        sa.Column("internal", sa.Boolean(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["ticket_id"], ["support_ticket.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_support_message_ticket_id"), "support_message", ["ticket_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_support_message_ticket_id"), table_name="support_message")
    op.drop_table("support_message")
    op.drop_index(op.f("ix_support_ticket_user_id"), table_name="support_ticket")
    op.drop_table("support_ticket")
    # ### end Alembic commands ###
