"""mcq kind, question families, quarantine levels, review checklists

Questions share the editorial workflow as content kind 'mcq'. Existing rows are lessons and keep working unchanged.

Revision ID: f439b2805593
Revises: 1bc0ea7902a1
Create Date: 2026-10-07 05:45:26.909662

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f439b2805593"
down_revision: str | Sequence[str] | None = "1bc0ea7902a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content_item", sa.Column("quarantine_level", sa.String(length=12), nullable=True))
    op.add_column("content_item", sa.Column("family_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_content_item_family_id"), "content_item", ["family_id"], unique=False)
    op.add_column(
        "review_decision",
        sa.Column("checklist", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
    )
    op.drop_constraint("content_item_kind", "content_item", type_="check")
    op.create_check_constraint("content_item_kind", "content_item", "kind in ('lesson', 'mcq')")
    op.create_check_constraint(
        "content_item_quarantine_level",
        "content_item",
        "quarantine_level is null or quarantine_level in ('SOFT', 'VOID', 'KEY_ERROR')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrading is only possible while no questions exist (the old constraint allows lessons only).
    op.drop_constraint("content_item_quarantine_level", "content_item", type_="check")
    op.drop_constraint("content_item_kind", "content_item", type_="check")
    op.create_check_constraint("content_item_kind", "content_item", "kind in ('lesson')")
    op.drop_column("review_decision", "checklist")
    op.drop_index(op.f("ix_content_item_family_id"), table_name="content_item")
    op.drop_column("content_item", "family_id")
    op.drop_column("content_item", "quarantine_level")
    # ### end Alembic commands ###
