"""per-question allowance, question outcomes, review capacity (review R05)

Revision ID: b1e32702b01c
Revises: c7a1e2f4b9d0
Create Date: 2026-10-08 10:29:11.868665

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b1e32702b01c"
down_revision: str | Sequence[str] | None = "c7a1e2f4b9d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "written_review_capacity",
        sa.Column("grade_number", sa.SmallInteger(), nullable=False),
        sa.Column("subject_code", sa.String(length=40), nullable=False),
        sa.Column("max_open_cases", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["updated_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("grade_number", "subject_code"),
    )
    op.add_column("allowance_event", sa.Column("position", sa.SmallInteger(), nullable=True))
    op.add_column("allowance_event", sa.Column("idempotency_key", sa.String(length=80), nullable=True))
    op.drop_constraint(op.f("uq_allowance_attempt_kind"), "allowance_event", type_="unique")
    op.create_index(
        "uq_allowance_attempt_kind_position",
        "allowance_event",
        ["attempt_id", "kind", sa.literal_column("coalesce(position, 0)")],
        unique=True,
        postgresql_where=sa.text("kind <> 'REMEDY_CREDIT'"),
    )
    op.create_index(
        "uq_allowance_remedy_key",
        "allowance_event",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text("kind = 'REMEDY_CREDIT'"),
    )
    op.add_column("written_review_case", sa.Column("positions", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("written_review_case", sa.Column("due_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "written_score_version",
        sa.Column("question_status", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
    )
    op.add_column(
        "written_score_version",
        sa.Column("completeness", sa.String(length=20), server_default="complete", nullable=False),
    )
    op.add_column("written_score_version", sa.Column("scored_max_units", sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.execute(
        "update allowance_event set idempotency_key = 'legacy-' || id::text where kind = 'REMEDY_CREDIT' and idempotency_key is null"
    )
    op.create_check_constraint(
        "allowance_remedy_key", "allowance_event", "kind <> 'REMEDY_CREDIT' or idempotency_key is not null"
    )
    op.drop_constraint("written_case_kind", "written_review_case", type_="check")
    op.create_check_constraint(
        "written_case_kind", "written_review_case", "case_kind in ('initial','recheck','completion')"
    )
    # Accepted work already queued gets the proposed 48 h service obligation from when it was opened.
    op.execute("update written_review_case set due_at = opened_at + interval '48 hours' where due_at is null")
    # No capacity rows are created: funded review capacity is an operator decision (R05). Until one is set, new written
    # starts are not offered in that scope; accepted work continues.


def downgrade() -> None:
    """Downgrade schema. Refused once per-question allowance events exist: the old one-event-per-kind rule can't
    represent them, and dropping ledger events would lose accounting history."""
    if op.get_bind().execute(sa.text("select 1 from allowance_event where position is not null limit 1")).scalar():
        raise RuntimeError("per-question allowance events exist; this downgrade would lose ledger history")
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("delete from written_review_case where case_kind = 'completion'")
    op.drop_constraint("written_case_kind", "written_review_case", type_="check")
    op.create_check_constraint("written_case_kind", "written_review_case", "case_kind in ('initial','recheck')")
    op.drop_constraint("allowance_remedy_key", "allowance_event", type_="check")
    op.drop_column("written_score_version", "scored_max_units")
    op.drop_column("written_score_version", "completeness")
    op.drop_column("written_score_version", "question_status")
    op.drop_column("written_review_case", "due_at")
    op.drop_column("written_review_case", "positions")
    op.drop_index(
        "uq_allowance_remedy_key", table_name="allowance_event", postgresql_where=sa.text("kind = 'REMEDY_CREDIT'")
    )
    op.drop_index(
        "uq_allowance_attempt_kind_position",
        table_name="allowance_event",
        postgresql_where=sa.text("kind <> 'REMEDY_CREDIT'"),
    )
    op.create_unique_constraint(
        op.f("uq_allowance_attempt_kind"),
        "allowance_event",
        ["attempt_id", "kind"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("allowance_event", "idempotency_key")
    op.drop_column("allowance_event", "position")
    op.drop_table("written_review_capacity")
    # ### end Alembic commands ###
