"""publication guard, completion successors, recheck rebases (review OCT8-02/03/04)

Existing stranded pending questions are repaired by `portal-written-repair` (idempotent, audited), not here.

Revision ID: 2365ef539356
Revises: d4f8a1c3e2b7
Create Date: 2026-10-08 13:16:26.838477

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2365ef539356"
down_revision: str | Sequence[str] | None = "d4f8a1c3e2b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "written_recheck_request",
        sa.Column("rebases", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
    )
    op.add_column("written_review_case", sa.Column("base_version", sa.SmallInteger(), nullable=True))
    op.add_column("written_review_case", sa.Column("predecessor_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "written_review_case_predecessor_fkey",
        "written_review_case",
        "written_review_case",
        ["predecessor_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("written_review_case_predecessor_fkey", "written_review_case", type_="foreignkey")
    op.drop_column("written_review_case", "predecessor_id")
    op.drop_column("written_review_case", "base_version")
    op.drop_column("written_recheck_request", "rebases")
    # ### end Alembic commands ###
