"""written questions and rubrics as content kinds

A rubric is a content item attached to one written question (parent_item_id). Existing rows are unaffected.

Revision ID: 224e4661b043
Revises: 63ccb2b043cd
Create Date: 2026-10-07 06:40:45.277874

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "224e4661b043"
down_revision: str | Sequence[str] | None = "63ccb2b043cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content_item", sa.Column("parent_item_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_content_item_parent_item_id"), "content_item", ["parent_item_id"], unique=False)
    op.create_foreign_key(
        "fk_content_item_parent", "content_item", "content_item", ["parent_item_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint("content_item_kind", "content_item", type_="check")
    op.create_check_constraint("content_item_kind", "content_item", "kind in ('lesson', 'mcq', 'written', 'rubric')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Possible only while no written questions or rubrics exist.
    op.drop_constraint("content_item_kind", "content_item", type_="check")
    op.create_check_constraint("content_item_kind", "content_item", "kind in ('lesson', 'mcq')")
    op.drop_constraint("fk_content_item_parent", "content_item", type_="foreignkey")
    op.drop_index(op.f("ix_content_item_parent_item_id"), table_name="content_item")
    op.drop_column("content_item", "parent_item_id")
    # ### end Alembic commands ###
