"""structured written recheck requests

Revision ID: 1bc0b73fea5b
Revises: 24d95c7ec9ae
Create Date: 2026-10-08 09:06:36.253390

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1bc0b73fea5b"
down_revision: str | Sequence[str] | None = "24d95c7ec9ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "written_recheck_request",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("target_version_id", sa.UUID(), nullable=False),
        sa.Column("positions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("expanded_positions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expansion_reason", sa.Text(), nullable=True),
        sa.Column("expanded_by", sa.UUID(), nullable=True),
        sa.Column("resolved_version_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status in ('open','resolved')", name="written_recheck_status"),
        sa.ForeignKeyConstraint(["attempt_id"], ["written_attempt.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["case_id"], ["written_review_case.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["expanded_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["requested_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["resolved_version_id"], ["written_score_version.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["target_version_id"], ["written_score_version.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
        sa.UniqueConstraint("target_version_id", name="uq_recheck_target_version"),
    )
    op.create_index(
        op.f("ix_written_recheck_request_attempt_id"), "written_recheck_request", ["attempt_id"], unique=False
    )
    # ### end Alembic commands ###
    _backfill()


def _backfill() -> None:
    """Pin recheck cases opened before this table existed. Their questions were kept as a "Questions 1, 2: reason"
    prefix; the target is the latest result released before the case opened. Cases that can't be pinned are left as
    they are and reported, never guessed."""
    import json
    import re
    import uuid

    bind = op.get_bind()
    cases = bind.execute(
        sa.text(
            "select c.id, c.attempt_id, c.opened_at, c.status, c.reason, a.user_id from written_review_case c "
            "join written_attempt a on a.id = c.attempt_id where c.case_kind = 'recheck' "
            "and not exists (select 1 from written_recheck_request r where r.case_id = c.id) order by c.opened_at"
        )
    ).all()
    for case_id, attempt_id, opened_at, status, reason, user_id in cases:
        target = bind.execute(
            sa.text(
                "select id from written_score_version where attempt_id = :a and released and created_at <= :t "
                "order by version desc limit 1"
            ),
            {"a": attempt_id, "t": opened_at},
        ).scalar()
        m = re.match(r"Questions ([\d, ]+): (.*)", reason or "", re.S)
        taken = (
            target
            and bind.execute(
                sa.text("select 1 from written_recheck_request where target_version_id = :v"), {"v": target}
            ).scalar()
        )
        if not target or not m or taken:
            print(f"recheck case {case_id}: not pinned (no target, unparsable reason or duplicate target)")
            continue
        positions = sorted({int(x) for x in m.group(1).replace(" ", "").split(",") if x})
        resolved = bind.execute(
            sa.text(
                "select id from written_score_version where case_id = :c and released order by version desc limit 1"
            ),
            {"c": case_id},
        ).scalar()
        bind.execute(
            sa.text(
                "insert into written_recheck_request (id, attempt_id, case_id, target_version_id, positions, criteria, "
                "reason, requested_by, status, expanded_positions, resolved_version_id, created_at) values "
                "(:id, :a, :c, :v, cast(:p as jsonb), '{}'::jsonb, :r, :u, :s, '[]'::jsonb, :rv, :t)"
            ),
            {
                "id": uuid.uuid4(),
                "a": attempt_id,
                "c": case_id,
                "v": target,
                "p": json.dumps(positions),
                "r": m.group(2).strip(),
                "u": user_id,
                "s": "resolved" if status == "released" else "open",
                "rv": resolved,
                "t": opened_at,
            },
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_written_recheck_request_attempt_id"), table_name="written_recheck_request")
    op.drop_table("written_recheck_request")
    # ### end Alembic commands ###
