"""catalogue retirement

Revision ID: effbc3a9555d
Revises: 3d04fc9cf35f
Create Date: 2026-10-07 04:04:07.038702

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "effbc3a9555d"
down_revision: str | Sequence[str] | None = "3d04fc9cf35f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chapter", sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f("chapter_book_id_display_order_key"), "chapter", type_="unique")
    op.create_index(
        "uq_chapter_order_active",
        "chapter",
        ["book_id", "display_order"],
        unique=True,
        postgresql_where=sa.text("retired_at is null"),
    )
    op.add_column("topic", sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f("topic_chapter_id_display_order_key"), "topic", type_="unique")
    op.create_index(
        "uq_topic_order_active",
        "topic",
        ["chapter_id", "display_order"],
        unique=True,
        postgresql_where=sa.text("retired_at is null"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_topic_order_active", table_name="topic", postgresql_where=sa.text("retired_at is null"))
    op.create_unique_constraint(
        op.f("topic_chapter_id_display_order_key"),
        "topic",
        ["chapter_id", "display_order"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("topic", "retired_at")
    op.drop_index("uq_chapter_order_active", table_name="chapter", postgresql_where=sa.text("retired_at is null"))
    op.create_unique_constraint(
        op.f("chapter_book_id_display_order_key"),
        "chapter",
        ["book_id", "display_order"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("chapter", "retired_at")
    # ### end Alembic commands ###
