"""written practice forms, attempts, evidence pages, receipts

Revision ID: db69629fbe8e
Revises: 224e4661b043
Create Date: 2026-10-07 07:04:55.376594

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "db69629fbe8e"
down_revision: str | Sequence[str] | None = "224e4661b043"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "written_form",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=80), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("grade_number", sa.SmallInteger(), nullable=False),
        sa.Column("subject_code", sa.String(length=40), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("question_type", sa.String(length=10), nullable=False),
        sa.Column("writing_s", sa.Integer(), nullable=True),
        sa.Column("upload_allowance_s", sa.Integer(), nullable=False),
        sa.Column("capture_policy_version", sa.SmallInteger(), nullable=False),
        sa.Column("caps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_units", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "idempotency_key", name="uq_written_form_idempotency"),
    )
    op.create_index(op.f("ix_written_form_owner_id"), "written_form", ["owner_id"], unique=False)
    op.create_table(
        "written_attempt",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("writing_deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("upload_allowance_s", sa.Integer(), nullable=False),
        sa.Column("upload_cutoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("manifest_revision", sa.Integer(), nullable=False),
        sa.CheckConstraint("status in ('active','sealed','expired')", name="written_attempt_status"),
        sa.ForeignKeyConstraint(["form_id"], ["written_form.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("form_id", "user_id", name="uq_written_attempt_form_user"),
    )
    op.create_index(op.f("ix_written_attempt_user_id"), "written_attempt", ["user_id"], unique=False)
    op.create_table(
        "written_page",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=40), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("pdf_pages", sa.SmallInteger(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("after_cutoff", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.CheckConstraint("status in ('uploaded','withdrawn')", name="written_page_status"),
        sa.ForeignKeyConstraint(["attempt_id"], ["written_attempt.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", "sha256", name="uq_written_page_attempt_hash"),
    )
    op.create_index(op.f("ix_written_page_attempt_id"), "written_page", ["attempt_id"], unique=False)
    op.create_table(
        "written_receipt",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=80), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("admitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("manifest_revision", sa.Integer(), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("page_hashes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("answered_slots", sa.SmallInteger(), nullable=False),
        sa.Column("unanswered_slots", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["attempt_id"], ["written_attempt.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id"),
    )
    op.create_table(
        "written_form_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("question_version_id", sa.UUID(), nullable=False),
        sa.Column("rubric_version_id", sa.UUID(), nullable=False),
        sa.Column("max_units", sa.Integer(), nullable=False),
        sa.Column("slots", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["form_id"], ["written_form.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["item_id"], ["content_item.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["question_version_id"], ["content_version.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["rubric_version_id"], ["content_version.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("form_id", "family_id"),
        sa.UniqueConstraint("form_id", "position"),
    )
    op.create_index(op.f("ix_written_form_item_form_id"), "written_form_item", ["form_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_written_form_item_form_id"), table_name="written_form_item")
    op.drop_table("written_form_item")
    op.drop_table("written_receipt")
    op.drop_index(op.f("ix_written_page_attempt_id"), table_name="written_page")
    op.drop_table("written_page")
    op.drop_index(op.f("ix_written_attempt_user_id"), table_name="written_attempt")
    op.drop_table("written_attempt")
    op.drop_index(op.f("ix_written_form_owner_id"), table_name="written_form")
    op.drop_table("written_form")
    # ### end Alembic commands ###
