"""curriculum and source registry

Revision ID: 4ee482d111db
Revises:
Create Date: 2026-10-06 23:22:02.095359

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4ee482d111db"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batch",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "region",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "source_document",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.String(length=40), nullable=False),
        sa.Column("grade_number", sa.SmallInteger(), nullable=False),
        sa.Column("subject_code", sa.String(length=40), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("authority", sa.Text(), nullable=True),
        sa.Column("edition", sa.Text(), nullable=True),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("pdf_pages", sa.Integer(), nullable=False),
        sa.Column("page_rule", sa.Text(), nullable=True),
        sa.Column("completeness", sa.String(length=20), nullable=False),
        sa.Column("missing_pages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duplicate_pages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rights", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id"),
    )
    op.create_table(
        "subject",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "grade",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("region_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.SmallInteger(), nullable=False),
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(["region_id"], ["region.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("region_id", "number"),
    )
    op.create_table(
        "book_edition",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("natural_key", sa.Text(), nullable=False),
        sa.Column("grade_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("chapter_label", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["grade_id"], ["grade.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_document_id"], ["source_document.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["subject_id"], ["subject.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("grade_id", "subject_id", "source_document_id"),
        sa.UniqueConstraint("natural_key"),
    )
    op.create_table(
        "chapter",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("natural_key", sa.Text(), nullable=False),
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column("number", sa.SmallInteger(), nullable=False),
        sa.Column("contents_number", sa.SmallInteger(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("printed_start", sa.Integer(), nullable=True),
        sa.Column("printed_end", sa.Integer(), nullable=True),
        sa.Column("pdf_start", sa.Integer(), nullable=True),
        sa.Column("pdf_end", sa.Integer(), nullable=True),
        sa.Column("slo_codes", sa.Text(), nullable=True),
        sa.Column("main_concept", sa.Text(), nullable=True),
        sa.Column("key_terms", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("visual_count", sa.Integer(), nullable=False),
        sa.Column("assessment_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_state", sa.String(length=40), nullable=False),
        sa.CheckConstraint("status in ('complete','partial','missing')", name="chapter_status"),
        sa.ForeignKeyConstraint(["book_id"], ["book_edition.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("book_id", "display_order"),
        sa.UniqueConstraint("natural_key"),
    )
    op.create_index(op.f("ix_chapter_book_id"), "chapter", ["book_id"], unique=False)
    op.create_index(
        "ix_chapter_title_trgm",
        "chapter",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_table(
        "topic",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("natural_key", sa.Text(), nullable=False),
        sa.Column("chapter_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("depth", sa.SmallInteger(), nullable=False),
        sa.Column("pdf_page", sa.Integer(), nullable=True),
        sa.Column("points", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapter.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["parent_id"], ["topic.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chapter_id", "display_order"),
        sa.UniqueConstraint("natural_key"),
    )
    op.create_index(op.f("ix_topic_chapter_id"), "topic", ["chapter_id"], unique=False)
    op.create_index(op.f("ix_topic_parent_id"), "topic", ["parent_id"], unique=False)
    op.create_index(
        "ix_topic_title_trgm",
        "topic",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_topic_title_trgm", table_name="topic", postgresql_using="gin", postgresql_ops={"title": "gin_trgm_ops"}
    )
    op.drop_index(op.f("ix_topic_parent_id"), table_name="topic")
    op.drop_index(op.f("ix_topic_chapter_id"), table_name="topic")
    op.drop_table("topic")
    op.drop_index(
        "ix_chapter_title_trgm", table_name="chapter", postgresql_using="gin", postgresql_ops={"title": "gin_trgm_ops"}
    )
    op.drop_index(op.f("ix_chapter_book_id"), table_name="chapter")
    op.drop_table("chapter")
    op.drop_table("book_edition")
    op.drop_table("grade")
    op.drop_table("subject")
    op.drop_table("source_document")
    op.drop_table("region")
    op.drop_table("import_batch")
    # ### end Alembic commands ###
