"""practice forms, attempts, answer ledger, receipts, score versions

Revision ID: 63ccb2b043cd
Revises: f439b2805593
Create Date: 2026-10-07 06:02:30.634673

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "63ccb2b043cd"
down_revision: str | Sequence[str] | None = "f439b2805593"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "practice_form",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=80), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("grade_number", sa.SmallInteger(), nullable=False),
        sa.Column("subject_code", sa.String(length=40), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("question_count", sa.SmallInteger(), nullable=False),
        sa.Column("duration_s", sa.Integer(), nullable=True),
        sa.Column("late_write_tolerance_ms", sa.Integer(), nullable=False),
        sa.Column("feedback_mode", sa.String(length=12), nullable=False),
        sa.Column("negative_marks", sa.SmallInteger(), nullable=False),
        sa.Column("invalid_item_treatment", sa.String(length=12), nullable=False),
        sa.Column("scoring_policy_version", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("feedback_mode in ('deferred','immediate')", name="practice_form_feedback_mode"),
        sa.CheckConstraint("invalid_item_treatment in ('EXCLUDE','CREDIT_ALL')", name="practice_form_invalid_item"),
        sa.CheckConstraint("question_count between 1 and 200", name="practice_form_count"),
        sa.ForeignKeyConstraint(["owner_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "idempotency_key", name="uq_practice_form_idempotency"),
    )
    op.create_index(op.f("ix_practice_form_owner_id"), "practice_form", ["owner_id"], unique=False)
    op.create_table(
        "attempt",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tolerance_ms", sa.Integer(), nullable=False),
        sa.Column("cutoff_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finalised_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finalise_reason", sa.String(length=10), nullable=True),
        sa.CheckConstraint("finalise_reason is null or finalise_reason in ('manual','expiry')", name="attempt_reason"),
        sa.CheckConstraint("status in ('active','finalised','void')", name="attempt_status"),
        sa.ForeignKeyConstraint(["form_id"], ["practice_form.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("form_id", "user_id", name="uq_attempt_form_user"),
    )
    op.create_index(
        "ix_attempt_active_cutoff",
        "attempt",
        ["cutoff_at"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(op.f("ix_attempt_user_id"), "attempt", ["user_id"], unique=False)
    op.create_table(
        "answer_op",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("op_id", sa.UUID(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("option_id", sa.String(length=12), nullable=True),
        sa.Column("admitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("disposition", sa.String(length=12), nullable=False),
        sa.Column("via", sa.String(length=10), nullable=False),
        sa.CheckConstraint(
            "disposition in ('accepted','stale','invalid','late','finalised','locked')", name="answer_op_disposition"
        ),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempt.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", "op_id", name="uq_answer_op"),
    )
    op.create_index(op.f("ix_answer_op_attempt_id"), "answer_op", ["attempt_id"], unique=False)
    op.create_table(
        "attempt_answer",
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("option_id", sa.String(length=12), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("op_id", sa.UUID(), nullable=False),
        sa.Column("saved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempt.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("attempt_id", "position"),
    )
    op.create_table(
        "score_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.SmallInteger(), nullable=False),
        sa.Column("scoring_policy_version", sa.SmallInteger(), nullable=False),
        sa.Column("adjudication_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=14), nullable=False),
        sa.Column("raw", sa.Integer(), nullable=False),
        sa.Column("maximum", sa.Integer(), nullable=False),
        sa.Column("percentage", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status in ('scored','not_scorable')", name="score_version_status"),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempt.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "attempt_id", "scoring_policy_version", "adjudication_hash", name="uq_score_effective_inputs"
        ),
        sa.UniqueConstraint("attempt_id", "version"),
    )
    op.create_index(op.f("ix_score_version_attempt_id"), "score_version", ["attempt_id"], unique=False)
    op.create_table(
        "submission_receipt",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=80), nullable=True),
        sa.Column("reason", sa.String(length=10), nullable=False),
        sa.Column("admitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("answered_count", sa.SmallInteger(), nullable=False),
        sa.Column("question_count", sa.SmallInteger(), nullable=False),
        sa.Column("ledger_hash", sa.String(length=64), nullable=False),
        sa.Column("included_ops", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempt.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id"),
    )
    op.create_table(
        "form_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("marks", sa.SmallInteger(), nullable=False),
        sa.Column("option_order", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["form_id"], ["practice_form.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["item_id"], ["content_item.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["version_id"], ["content_version.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("form_id", "family_id", name="uq_form_item_family"),
        sa.UniqueConstraint("form_id", "position"),
    )
    op.create_index(op.f("ix_form_item_form_id"), "form_item", ["form_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_form_item_form_id"), table_name="form_item")
    op.drop_table("form_item")
    op.drop_table("submission_receipt")
    op.drop_index(op.f("ix_score_version_attempt_id"), table_name="score_version")
    op.drop_table("score_version")
    op.drop_table("attempt_answer")
    op.drop_index(op.f("ix_answer_op_attempt_id"), table_name="answer_op")
    op.drop_table("answer_op")
    op.drop_index(op.f("ix_attempt_user_id"), table_name="attempt")
    op.drop_index("ix_attempt_active_cutoff", table_name="attempt", postgresql_where=sa.text("status = 'active'"))
    op.drop_table("attempt")
    op.drop_index(op.f("ix_practice_form_owner_id"), table_name="practice_form")
    op.drop_table("practice_form")
    # ### end Alembic commands ###
