"""identity roles consent audit

Revision ID: 3d04fc9cf35f
Revises: 4ee482d111db
Create Date: 2026-10-07 00:30:01.143375

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3d04fc9cf35f"
down_revision: str | Sequence[str] | None = "4ee482d111db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issuer", sa.Text(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status in ('active','suspended','deleted')", name="app_user_status"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issuer", "subject"),
    )
    op.create_index(op.f("ix_app_user_email"), "app_user", ["email"], unique=False)
    op.create_table(
        "audit_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.String(length=80), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["actor_user_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_event_actor_user_id"), "audit_event", ["actor_user_id"], unique=False)
    op.create_index(op.f("ix_audit_event_at"), "audit_event", ["at"], unique=False)
    op.create_index("ix_audit_event_target", "audit_event", ["target_type", "target_id"], unique=False)
    op.create_table(
        "consent_record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("document", sa.String(length=40), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_consent_record_user_id"), "consent_record", ["user_id"], unique=False)
    op.create_table(
        "dev_credential",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "staff_role_grant",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.UUID(), nullable=True),
        sa.Column("revoke_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["granted_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["revoked_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_staff_role_grant_active",
        "staff_role_grant",
        ["user_id", "role"],
        unique=False,
        postgresql_where="revoked_at is null",
    )
    op.create_index(op.f("ix_staff_role_grant_user_id"), "staff_role_grant", ["user_id"], unique=False)
    op.create_table(
        "student_profile",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("grade", sa.SmallInteger(), nullable=True),
        sa.Column("stream", sa.String(length=30), nullable=True),
        sa.Column("subjects", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_exams", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_year", sa.SmallInteger(), nullable=True),
        sa.Column("explanation_language", sa.String(length=12), nullable=False),
        sa.Column("daily_minutes", sa.SmallInteger(), nullable=True),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("daily_minutes is null or daily_minutes between 10 and 600", name="student_profile_minutes"),
        sa.CheckConstraint("grade is null or grade in (11, 12)", name="student_profile_grade"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_profile")
    op.drop_index(op.f("ix_staff_role_grant_user_id"), table_name="staff_role_grant")
    op.drop_index("ix_staff_role_grant_active", table_name="staff_role_grant", postgresql_where="revoked_at is null")
    op.drop_table("staff_role_grant")
    op.drop_table("dev_credential")
    op.drop_index(op.f("ix_consent_record_user_id"), table_name="consent_record")
    op.drop_table("consent_record")
    op.drop_index("ix_audit_event_target", table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_at"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_actor_user_id"), table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_index(op.f("ix_app_user_email"), table_name="app_user")
    op.drop_table("app_user")
    # ### end Alembic commands ###
