"""notifications

Revision ID: 20ca22d182aa
Revises: 9d1c3a7e5b20
Create Date: 2026-10-09 00:22:22.643300

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20ca22d182aa"
down_revision: str | Sequence[str] | None = "9d1c3a7e5b20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("event", sa.String(length=40), nullable=False),
        sa.Column("category", sa.String(length=12), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("link", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("category in ('service','reminder','promotional')", name="notification_category"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "dedupe_key", name="uq_notification_dedupe"),
    )
    op.create_index(
        "ix_notification_unread", "notification", ["user_id"], unique=False, postgresql_where=sa.text("read_at is null")
    )
    op.create_index("ix_notification_user_created", "notification", ["user_id", "created_at"], unique=False)
    op.create_table(
        "notification_preference",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("push_enabled", sa.Boolean(), nullable=False),
        sa.Column("reminders_enabled", sa.Boolean(), nullable=False),
        sa.Column("promotional_opt_in", sa.Boolean(), nullable=False),
        sa.Column("timezone", sa.String(length=60), nullable=False),
        sa.Column("quiet_start", sa.String(length=5), nullable=False),
        sa.Column("quiet_end", sa.String(length=5), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "push_token",
        sa.Column("token", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.CheckConstraint("platform in ('ios','android')", name="push_token_platform"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index(op.f("ix_push_token_user_id"), "push_token", ["user_id"], unique=False)
    op.create_table(
        "notification_delivery",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("notification_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("urgent", sa.Boolean(), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("provider_ref", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("channel in ('email','push','sms')", name="notification_delivery_channel"),
        sa.CheckConstraint(
            "status in ('queued','sent','failed','skipped','unavailable')", name="notification_delivery_status"
        ),
        sa.ForeignKeyConstraint(["notification_id"], ["notification.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("notification_id", "channel", name="uq_notification_delivery"),
    )
    op.create_index(
        "ix_notification_delivery_due",
        "notification_delivery",
        ["next_attempt_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(op.f("ix_notification_delivery_user_id"), "notification_delivery", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_delivery_user_id"), table_name="notification_delivery")
    op.drop_index(
        "ix_notification_delivery_due",
        table_name="notification_delivery",
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.drop_table("notification_delivery")
    op.drop_index(op.f("ix_push_token_user_id"), table_name="push_token")
    op.drop_table("push_token")
    op.drop_table("notification_preference")
    op.drop_index("ix_notification_user_created", table_name="notification")
    op.drop_index("ix_notification_unread", table_name="notification", postgresql_where=sa.text("read_at is null"))
    op.drop_table("notification")
    # ### end Alembic commands ###
