"""trial grants, entitlements, written allowance ledger

Revision ID: eea7fd88f3f1
Revises: b4c149c0d98e
Create Date: 2026-10-07 07:52:14.908087

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eea7fd88f3f1"
down_revision: str | Sequence[str] | None = "b4c149c0d98e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entitlement",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=12), nullable=False),
        sa.Column("product_code", sa.String(length=40), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("written_units", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoke_reason", sa.Text(), nullable=True),
        sa.CheckConstraint("source in ('trial','paid','scholarship','promotional','pilot')", name="entitlement_source"),
        sa.CheckConstraint("status in ('active','revoked','refunded')", name="entitlement_status"),
        sa.CheckConstraint("ends_at > starts_at", name="entitlement_period"),
        sa.ForeignKeyConstraint(["granted_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entitlement_user_id"), "entitlement", ["user_id"], unique=False)
    op.create_table(
        "allowance_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("entitlement_id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=14), nullable=False),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind in ('RESERVED','ACCEPTED','CONSUMED','RELEASED','REMEDY_CREDIT')", name="allowance_event_kind"
        ),
        sa.ForeignKeyConstraint(["entitlement_id"], ["entitlement.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", "kind", name="uq_allowance_attempt_kind"),
    )
    op.create_index(op.f("ix_allowance_event_attempt_id"), "allowance_event", ["attempt_id"], unique=False)
    op.create_index(op.f("ix_allowance_event_entitlement_id"), "allowance_event", ["entitlement_id"], unique=False)
    op.create_index(op.f("ix_allowance_event_user_id"), "allowance_event", ["user_id"], unique=False)
    op.create_table(
        "trial_grant",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("program", sa.String(length=40), nullable=False),
        sa.Column("offer_terms_version", sa.SmallInteger(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("client", sa.String(length=10), nullable=False),
        sa.Column("entitlement_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["entitlement_id"], ["entitlement.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "program", name="uq_trial_grant_program"),
    )
    op.create_index(op.f("ix_trial_grant_user_id"), "trial_grant", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trial_grant_user_id"), table_name="trial_grant")
    op.drop_table("trial_grant")
    op.drop_index(op.f("ix_allowance_event_user_id"), table_name="allowance_event")
    op.drop_index(op.f("ix_allowance_event_entitlement_id"), table_name="allowance_event")
    op.drop_index(op.f("ix_allowance_event_attempt_id"), table_name="allowance_event")
    op.drop_table("allowance_event")
    op.drop_index(op.f("ix_entitlement_user_id"), table_name="entitlement")
    op.drop_table("entitlement")
    # ### end Alembic commands ###
