"""content workflow and publication rights

Editorial items, immutable-once-submitted versions, review decisions (P06) and the owner's publication-rights gate on
source documents. Existing sources start UNVERIFIED, which blocks publication of derived material only.

Revision ID: 1bc0ea7902a1
Revises: 44f4ff1cdd6f
Create Date: 2026-10-07 05:05:40.320299

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1bc0ea7902a1"
down_revision: str | Sequence[str] | None = "44f4ff1cdd6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("chapter_id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=True),
        sa.Column("grade_number", sa.SmallInteger(), nullable=False),
        sa.Column("subject_code", sa.String(length=40), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("availability", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("assigned_reviewer_id", sa.UUID(), nullable=True),
        sa.Column("working_version_id", sa.UUID(), nullable=True),
        sa.Column("published_version_id", sa.UUID(), nullable=True),
        sa.Column("availability_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "availability in ('unpublished', 'live', 'quarantined', 'retired')", name="content_item_availability"
        ),
        sa.CheckConstraint(
            "availability not in ('live','quarantined') or published_version_id is not null",
            name="content_item_live_has_version",
        ),
        sa.CheckConstraint("kind in ('lesson')", name="content_item_kind"),
        sa.CheckConstraint(
            "state in ('draft', 'submitted', 'changes_requested', 'approved', 'published')", name="content_item_state"
        ),
        sa.ForeignKeyConstraint(["assigned_reviewer_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapter.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["topic_id"], ["topic.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_content_item_chapter_id"), "content_item", ["chapter_id"], unique=False)
    op.create_index(
        "ix_content_item_live",
        "content_item",
        ["chapter_id"],
        unique=False,
        postgresql_where=sa.text("availability = 'live'"),
    )
    op.create_index("ix_content_item_queue", "content_item", ["state", "grade_number", "subject_code"], unique=False)
    op.create_index(op.f("ix_content_item_topic_id"), "content_item", ["topic_id"], unique=False)
    op.create_table(
        "content_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("content_schema_version", sa.SmallInteger(), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("block_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("contributors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status in ('draft', 'submitted', 'changes_requested', 'approved', 'published', 'superseded')",
            name="content_version_status",
        ),
        sa.ForeignKeyConstraint(["approved_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["item_id"], ["content_item.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["published_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["app_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_content_version_item_id"), "content_version", ["item_id"], unique=False)
    op.create_index("uq_content_version_number", "content_version", ["item_id", "number"], unique=True)
    op.create_index(
        "uq_content_version_one_published",
        "content_version",
        ["item_id"],
        unique=True,
        postgresql_where=sa.text("status = 'published'"),
    )
    op.create_table(
        "review_decision",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("decision in ('approve','request_changes')", name="review_decision_decision"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["app_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["version_id"], ["content_version.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_decision_version_id"), "review_decision", ["version_id"], unique=False)
    # content_item <-> content_version reference each other; add the item's pointers once both tables exist.
    op.create_foreign_key(
        "fk_item_working_version",
        "content_item",
        "content_version",
        ["working_version_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_item_published_version",
        "content_item",
        "content_version",
        ["published_version_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "source_document",
        sa.Column("publication_rights", sa.String(length=12), server_default="UNVERIFIED", nullable=False),
    )
    op.add_column("source_document", sa.Column("publication_rights_evidence", sa.Text(), nullable=True))
    op.add_column("source_document", sa.Column("publication_rights_set_by", sa.UUID(), nullable=True))
    op.add_column("source_document", sa.Column("publication_rights_set_at", sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        "fk_source_document_rights_set_by",
        "source_document",
        "app_user",
        ["publication_rights_set_by"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        "source_document_publication_rights",
        "source_document",
        "publication_rights in ('UNVERIFIED','CONFIRMED','DENIED')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("source_document_publication_rights", "source_document", type_="check")
    op.drop_constraint("fk_source_document_rights_set_by", "source_document", type_="foreignkey")
    op.drop_column("source_document", "publication_rights_set_at")
    op.drop_column("source_document", "publication_rights_set_by")
    op.drop_column("source_document", "publication_rights_evidence")
    op.drop_column("source_document", "publication_rights")
    op.drop_constraint("fk_item_published_version", "content_item", type_="foreignkey")
    op.drop_constraint("fk_item_working_version", "content_item", type_="foreignkey")
    op.drop_index(op.f("ix_review_decision_version_id"), table_name="review_decision")
    op.drop_table("review_decision")
    op.drop_index(
        "uq_content_version_one_published",
        table_name="content_version",
        postgresql_where=sa.text("status = 'published'"),
    )
    op.drop_index("uq_content_version_number", table_name="content_version")
    op.drop_index(op.f("ix_content_version_item_id"), table_name="content_version")
    op.drop_table("content_version")
    op.drop_index(op.f("ix_content_item_topic_id"), table_name="content_item")
    op.drop_index("ix_content_item_queue", table_name="content_item")
    op.drop_index("ix_content_item_live", table_name="content_item", postgresql_where=sa.text("availability = 'live'"))
    op.drop_index(op.f("ix_content_item_chapter_id"), table_name="content_item")
    op.drop_table("content_item")
    # ### end Alembic commands ###
