"""Build the Class 11 and Class 12 master indexes, subject indexes, class-level visual/assessment
indexes and the library manifest from the per-book JSON records.

Usage (from the project root):
    python education_knowledge/tools/build_indexes.py

Inputs : education_knowledge/indexes/class_<11|12>/<subject>/<slug>_book.json   (hand-curated per book)
Outputs: education_knowledge/Class_11_Master_Index.md
         education_knowledge/Class_12_Master_Index.md
         education_knowledge/indexes/class_<n>/<subject>/<subject>_subject_index.md
         education_knowledge/indexes/class_<n>/class_<n>_visual_index.md
         education_knowledge/indexes/class_<n>/class_<n>_assessment_index.md
         education_knowledge/indexes/class_<n>/class_<n>_knowledge_map.json
         education_knowledge/Academic_Library_Index_Manifest.md
Class 11 and Class 12 are processed completely separately; no output file mixes the two classes.
Never edit generated files by hand: fix the per-book JSON/MD and re-run.
"""
import json, glob, os, re, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJ = os.path.dirname(ROOT)
SUBJECT_ORDER = ["physics", "chemistry", "biology", "mathematics", "computer_science"]
SUBJECT_NAME = {"physics": "Physics", "chemistry": "Chemistry", "biology": "Biology",
                "mathematics": "Mathematics", "computer_science": "Computer Science"}
DATE = datetime.date.today().isoformat()
GEN = ("> Generated by `tools/build_indexes.py` on {d} from the per-book JSON records. "
       "Do not edit by hand.\n").format(d=DATE)
QTYPES = ["MCQ", "FillBlank", "TrueFalse", "Matching", "Short", "Constructed", "Long", "Numerical",
          "Exercise", "Derivation", "Practical", "DiagramBased", "GraphBased", "TableBased",
          "Conceptual", "Application", "Project", "Other"]


def rel(path):
    return os.path.relpath(path, ROOT).replace("\\", "/")


def load_class(cls):
    books = []
    for fn in glob.glob(os.path.join(ROOT, "indexes", f"class_{cls}", "*", "*_book.json")):
        with open(fn, encoding="utf-8") as f:
            b = json.load(f)
        if int(b.get("class", 0)) != cls:
            raise SystemExit(f"CLASS MISMATCH: {fn} says class {b.get('class')} but sits in class_{cls}")
        b["_dir"] = os.path.dirname(fn)
        b["_json"] = rel(fn)
        slug = b.get("book_slug") or os.path.basename(fn)[:-10]
        b["_md"] = rel(os.path.join(b["_dir"], slug + "_book_index.md"))
        b["_vis"] = rel(os.path.join(b["_dir"], slug + "_visual_index.md"))
        b["_subject"] = os.path.basename(b["_dir"])
        books.append(b)
    books.sort(key=lambda b: (SUBJECT_ORDER.index(b["_subject"]) if b["_subject"] in SUBJECT_ORDER else 99, b["book_id"]))
    return books


def pg(v):
    return "?" if v in (None, "", 0) else str(v)


def rng(a, z):
    return "—" if a in (None, "", 0) and z in (None, "", 0) else f"{pg(a)}–{pg(z)}"


def walk(topics, depth=0):
    for t in topics or []:
        if isinstance(t, str):          # topic phrase listed under a heading
            t = {"id": None, "title": t}
        yield depth, t
        yield from walk(t.get("subtopics"), depth + 1)


def tid(t):
    i = t.get("id")
    return i if i and re.search(r"\d", str(i)) else None


def tline(t, d):
    i = tid(t)
    lab = f"{i} {t.get('title', '')}" if i else f"{t.get('title', '')} *(unnumbered)*"
    p = t.get("pdf_page")
    return "  " * d + f"- {lab}" + (f" — PDF p.{p}" if p else "")


def status(ch):
    s = (ch.get("status") or "complete").lower()
    return "" if s == "complete" else f" **[{s.upper()}]**"


def qcount(ch):
    out = {k: 0 for k in QTYPES}
    for a in ch.get("assessment") or []:
        t = a.get("type") or "Other"
        c = a.get("count")
        if t not in out:
            t = "Other"
        if isinstance(c, (int, float)):
            out[t] += int(c)
    return out


def vcount(ch):
    out = {}
    for v in ch.get("visuals") or []:
        out[v.get("type") or "Other"] = out.get(v.get("type") or "Other", 0) + 1
    return out


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote", rel(path))


# ---------------------------------------------------------------- subject index
def build_subject_index(cls, subj, books):
    name = SUBJECT_NAME.get(subj, subj)
    L = [f"# Class {cls} {name} — Subject Index\n", GEN,
         f"Scope: **Class {cls} only.** Books: {', '.join(b['book_id'] for b in books)}.\n"]
    for b in books:
        L.append(f"## Book: {b.get('title')} ({b['book_id']})\n")
        L.append(f"- File: `{b.get('filename')}` · {b.get('pdf_pages')} PDF pages · {b.get('file_type')}  ")
        L.append(f"- Page rule: {b.get('page_rule')} · Completeness: **{(b.get('completeness') or {}).get('status', '?')}**  ")
        L.append(f"- Book index: `{b['_md']}` · Visual index: `{b['_vis']}` · JSON: `{b['_json']}` · Text layer: `{b.get('text_layer')}`\n")
        L.append("### Chapters\n")
        L.append("| Ch | Title | PDF pp. | Printed pp. | Topics | Visuals | Questions | Status |")
        L.append("|---|---|---|---|---|---|---|---|")
        for ch in b.get("chapters", []):
            nt = sum(1 for d, t in walk(ch.get("topics")) if tid(t))
            nv = len(ch.get("visuals") or [])
            nq = sum(qcount(ch).values())
            L.append(f"| {ch.get('number')} | {ch.get('title')} | {rng(ch.get('pdf_start'), ch.get('pdf_end'))} | "
                     f"{rng(ch.get('printed_start'), ch.get('printed_end'))} | {nt} | {nv} | {nq} | {ch.get('status') or 'complete'} |")
        L.append("\n### Major topics per chapter\n")
        for ch in b.get("chapters", []):
            tops = [t.get("title") for d, t in walk(ch.get("topics")) if d == 0]
            L.append(f"- **Ch {ch.get('number')} {ch.get('title')}:** " + "; ".join(tops))
        L.append("\n### Diagram / visual locations\n")
        L.append("| Ch | Visual counts by type | PDF pages with visuals |")
        L.append("|---|---|---|")
        for ch in b.get("chapters", []):
            vc = vcount(ch)
            pages = sorted({v.get("pdf_page") for v in ch.get("visuals") or [] if v.get("pdf_page")})
            L.append(f"| {ch.get('number')} | {', '.join(f'{k} {v}' for k, v in sorted(vc.items())) or '—'} | {compress(pages)} |")
        L.append("\n### Formula / law locations\n")
        for ch in b.get("chapters", []):
            f_ = ch.get("formulas") or []
            lw = ch.get("laws_principles") or []
            if f_ or lw:
                L.append(f"- **Ch {ch.get('number')}:** " + "; ".join([str(x) for x in lw] + [str(x) for x in f_]))
        L.append("\n### Exercise / assessment locations\n")
        L.append("| Ch | Section | Type | Count | PDF pp. |")
        L.append("|---|---|---|---|---|")
        for ch in b.get("chapters", []):
            for a in ch.get("assessment") or []:
                pp = a.get("pdf_pages") or []
                L.append(f"| {ch.get('number')} | {a.get('section')} | {a.get('type')} | {a.get('count')} | {rng(pp[0], pp[-1]) if pp else '—'} |")
        if b.get("back_matter"):
            L.append("\n### Back matter / assessment material\n")
            for m in b["back_matter"]:
                L.append(f"- {m.get('name')} — PDF {rng(m.get('pdf_start'), m.get('pdf_end'))}: {m.get('description', '')}")
        L.append("")
    return "\n".join(L) + "\n"


def compress(pages):
    if not pages:
        return "—"
    out, start, prev = [], pages[0], pages[0]
    for p in pages[1:]:
        if p == prev + 1:
            prev = p
            continue
        out.append(f"{start}" if start == prev else f"{start}–{prev}")
        start = prev = p
    out.append(f"{start}" if start == prev else f"{start}–{prev}")
    return ", ".join(out)


# ---------------------------------------------------------------- class visual index
def build_visual_index(cls, books):
    L = [f"# Class {cls} — Visual Index\n", GEN,
         "Every academically relevant diagram, figure, table, graph, chart, flowchart, structure, apparatus and code listing "
         f"recorded for Class {cls}. Full entries (labels, what it represents, importance) are in each book's `*_visual_index.md`.\n"]
    tot = {}
    for b in books:
        L.append(f"## {SUBJECT_NAME.get(b['_subject'], b['_subject'])} — {b.get('title')} ({b['book_id']})\n")
        L.append(f"File `{b.get('filename')}` · detail: `{b['_vis']}`\n")
        for ch in b.get("chapters", []):
            vs = ch.get("visuals") or []
            if not vs:
                continue
            L.append(f"### Ch {ch.get('number')} — {ch.get('title')} ({len(vs)} visuals)\n")
            L.append("| Visual ID | Type | PDF p | Printed p | Caption / identifier | Topic |")
            L.append("|---|---|---|---|---|---|")
            for v in vs:
                cap = (v.get("caption") or "").replace("|", "/")
                if v.get("official_caption") is False:
                    cap += " *(descriptive)*"
                L.append(f"| {v.get('visual_id')} | {v.get('type')} | {pg(v.get('pdf_page'))} | {pg(v.get('printed_page'))} | {cap} | {v.get('topic_id') or ''} |")
                tot[v.get("type") or "Other"] = tot.get(v.get("type") or "Other", 0) + 1
            L.append("")
    L.insert(3, "**Totals by type:** " + ", ".join(f"{k} {v}" for k, v in sorted(tot.items())) + f" — **{sum(tot.values())} visuals**\n")
    return "\n".join(L) + "\n", sum(tot.values())


# ---------------------------------------------------------------- class assessment index
def build_assessment_index(cls, books):
    L = [f"# Class {cls} — Assessment Index\n", GEN,
         "Question material as printed in the textbooks, by chapter and type (types kept separate as the books structure them). "
         "Counts are from the per-book records; question text lives in the source PDFs at the pages given.\n"]
    grand = {k: 0 for k in QTYPES}
    for b in books:
        L.append(f"## {SUBJECT_NAME.get(b['_subject'], b['_subject'])} — {b.get('title')} ({b['book_id']})\n")
        L.append("| Ch | Section (as printed) | Type | Count | PDF pp. | Notes |")
        L.append("|---|---|---|---|---|---|")
        tot = {k: 0 for k in QTYPES}
        for ch in b.get("chapters", []):
            for a in ch.get("assessment") or []:
                pp = a.get("pdf_pages") or []
                t = a.get("type") if a.get("type") in QTYPES else "Other"
                if isinstance(a.get("count"), (int, float)):
                    tot[t] += int(a["count"])
                L.append(f"| {ch.get('number')} | {a.get('section')} | {t} | {a.get('count')} | {rng(pp[0], pp[-1]) if pp else '—'} | {(a.get('notes') or '')[:80]} |")
        L.append("| **Total** | | | " + ", ".join(f"{k} {v}" for k, v in tot.items() if v) + " | | |\n")
        L.append("**Answer availability:** " + "; ".join(f"Ch {ch.get('number')}: {ch.get('answers_available', '?')}" for ch in b.get("chapters", [])) + "\n")
        for m in b.get("back_matter") or []:
            if re.search(r"pairing|model|paper|answer", m.get("name", ""), re.I):
                L.append(f"- Back matter: **{m.get('name')}** — PDF {rng(m.get('pdf_start'), m.get('pdf_end'))}: {m.get('description', '')}")
        L.append("")
        for k in grand:
            grand[k] += tot[k]
    L.insert(3, "**Class totals:** " + ", ".join(f"{k} {v}" for k, v in grand.items() if v) + "\n")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- master index
def build_master(cls, books, nvis):
    L = [f"# Class {cls} Master Index\n", GEN,
         f"**Scope:** Class {cls} only. This index points to information; the current PDFs in `{cls} Class Data/` remain the "
         "authoritative content. Route: Master Index → subject → book index → chapter → original PDF pages.\n",
         "## Library Summary\n"]
    nch = sum(len(b.get("chapters", [])) for b in books)
    ntop = sum(1 for b in books for ch in b.get("chapters", []) for d, t in walk(ch.get("topics")) if tid(t))
    nq = sum(sum(qcount(ch).values()) for b in books for ch in b.get("chapters", []))
    subjects = sorted({b["_subject"] for b in books}, key=lambda s: SUBJECT_ORDER.index(s) if s in SUBJECT_ORDER else 99)
    L += [f"- Total subjects: **{len(subjects)}** ({', '.join(SUBJECT_NAME.get(s, s) for s in subjects)})",
          f"- Total books: **{len(books)}**", f"- Total chapters: **{nch}**",
          f"- Total numbered topics/subtopics: **{ntop}**", f"- Total visuals indexed: **{nvis}**",
          f"- Total textbook questions indexed: **{nq}**",
          f"- Text layers: `source_text/` · Visual index: `indexes/class_{cls}/class_{cls}_visual_index.md` · "
          f"Assessment index: `indexes/class_{cls}/class_{cls}_assessment_index.md`\n", "## Subjects\n"]
    for s in subjects:
        sb = [b for b in books if b["_subject"] == s]
        L.append(f"### {SUBJECT_NAME.get(s, s)}\n")
        L.append(f"- Subject index: `indexes/class_{cls}/{s}/{s}_subject_index.md`")
        for b in sb:
            chs = b.get("chapters", [])
            L.append(f"- Book: **{b.get('title')}** ({b['book_id']}) — `{b.get('filename')}` · {b.get('pdf_pages')} PDF pp · "
                     f"{len(chs)} chapters ({chs[0].get('number') if chs else '?'}–{chs[-1].get('number') if chs else '?'}) · "
                     f"completeness: {(b.get('completeness') or {}).get('status', '?')}")
            L.append(f"  - Book index: `{b['_md']}` · Visual index: `{b['_vis']}` · JSON: `{b['_json']}`")
            L.append("  - Chapters: " + "; ".join(f"{ch.get('number')} {ch.get('title')}" for ch in chs))
            maj = []
            for ch in chs:
                maj += [t.get("title") for d, t in walk(ch.get("topics")) if d == 0][:3]
            L.append("  - Major topics (first three per chapter): " + "; ".join(x for x in maj if x))
        L.append("")
    L.append("## Master Chapter Map\n")
    L.append("Subject → Book → Chapter → Topics → Page range → Visuals → Exercises. Topics are shown two levels deep; "
             "the full tree with deeper subtopics is in the book index files.\n")
    for b in books:
        L.append(f"### {SUBJECT_NAME.get(b['_subject'], b['_subject'])} → {b.get('title')} ({b['book_id']})\n")
        for ch in b.get("chapters", []):
            vc = vcount(ch)
            qc = qcount(ch)
            L.append(f"#### Ch {ch.get('number')} — {ch.get('title')}{status(ch)}")
            L.append(f"PDF {rng(ch.get('pdf_start'), ch.get('pdf_end'))} · printed {rng(ch.get('printed_start'), ch.get('printed_end'))}"
                     + (f" · SLOs {ch['slo_codes']}" if ch.get("slo_codes") and "not printed" not in str(ch.get("slo_codes")).lower() and "unverified" not in str(ch.get("slo_codes")).lower() else ""))
            if ch.get("main_concept"):
                L.append(f"\n*{ch['main_concept']}*\n")
            for d, t in walk(ch.get("topics")):
                if d <= 1:
                    L.append(tline(t, d))
            L.append(f"\n- Visuals: {', '.join(f'{k} {v}' for k, v in sorted(vc.items())) or 'none recorded'}"
                     + (f" — e.g. {', '.join(v.get('visual_id','') for v in (ch.get('visuals') or [])[:4])}" if ch.get("visuals") else ""))
            ex = [a for a in ch.get("assessment") or []]
            L.append("- Exercises: " + ("; ".join(f"{a.get('section')} ({a.get('count')})" for a in ex) if ex else "none recorded")
                     + f" · answers: {ch.get('answers_available', '?')}")
            if ch.get("formulas"):
                L.append("- Key formulas/laws: " + "; ".join(str(x) for x in (ch.get("laws_principles") or []) + ch["formulas"])[:600])
            L.append("")
    L.append("## Visual Index Reference\n")
    L.append(f"- Class-level: `indexes/class_{cls}/class_{cls}_visual_index.md` ({nvis} visuals)")
    for b in books:
        L.append(f"- {b['book_id']}: `{b['_vis']}` — {sum(len(ch.get('visuals') or []) for ch in b.get('chapters', []))} visuals")
    L.append("\n## Assessment Index Reference\n")
    L.append(f"- Class-level: `indexes/class_{cls}/class_{cls}_assessment_index.md`")
    for b in books:
        qc = {k: 0 for k in QTYPES}
        for ch in b.get("chapters", []):
            for k, v in qcount(ch).items():
                qc[k] += v
        L.append(f"- {b['book_id']}: " + ", ".join(f"{k} {v}" for k, v in qc.items() if v))
        for m in b.get("back_matter") or []:
            if re.search(r"pairing|model|paper", m.get("name", ""), re.I):
                L.append(f"  - {m.get('name')} — PDF {rng(m.get('pdf_start'), m.get('pdf_end'))}")
    L.append("\n## Known File Issues\n")
    any_issue = False
    for b in books:
        comp = b.get("completeness") or {}
        items = list(b.get("issues") or [])
        if comp.get("missing_pages"):
            items.insert(0, f"Missing pages: {comp['missing_pages']}")
        if comp.get("duplicate_pages"):
            items.insert(0, f"Duplicate pages: {comp['duplicate_pages']}")
        items += comp.get("notes") or []
        if items:
            any_issue = True
            L.append(f"- **{b['book_id']}** (`{b.get('filename')}`, status {comp.get('status', '?')}):")
            for i in items:
                L.append(f"  - {i}")
    if not any_issue:
        L.append("- none recorded")
    L.append("\n## Duplicate/Replaced PDF Record\n")
    L.append(f"- No duplicate books in the current `{cls} Class Data/` folder: each of the {len(books)} files is a distinct subject textbook (verified by inventory).")
    L.append("- All current files REPLACE the earlier studyplusplus.com scans indexed on 2026-10-06 (v1). The v1 index is archived in "
             "`_archive/v1_2026-10-06_studyplusplus_scans/` for reference only; it is NOT authoritative and its page numbers do not apply to the current files.")
    L.append("- Current file is PRIMARY SOURCE for every book listed above.")
    L.append(f"\n## Last Index Validation\n\n- Built {DATE} by `tools/build_indexes.py`; validation record in `tools/verify_knowledge_base.py` output and `Academic_Library_Index_Manifest.md`.\n")
    return "\n".join(L) + "\n"


def build_manifest(data):
    L = ["# Academic Library Index Manifest\n", GEN,
         "Entry point to the Class 11 and Class 12 knowledge bases. The two classes are separate systems; this file only lists where "
         "their indexes live and contains no academic content.\n",
         "Source-of-truth hierarchy: **Original current PDF → per-book index → subject index → class master index.**\n"]
    for cls in (11, 12):
        books, nvis = data[cls]
        L.append(f"## Class {cls}\n")
        L.append(f"Master Index: `Class_{cls}_Master_Index.md`  ")
        L.append(f"Visual Index: `indexes/class_{cls}/class_{cls}_visual_index.md` · Assessment Index: `indexes/class_{cls}/class_{cls}_assessment_index.md` · "
                 f"Knowledge map (JSON): `indexes/class_{cls}/class_{cls}_knowledge_map.json`\n")
        L.append("Subjects:")
        for s in sorted({b["_subject"] for b in books}, key=lambda s: SUBJECT_ORDER.index(s) if s in SUBJECT_ORDER else 99):
            L.append(f"- {SUBJECT_NAME.get(s, s)} → `indexes/class_{cls}/{s}/{s}_subject_index.md`")
        L.append("\nBooks:")
        for b in books:
            L.append(f"- {b.get('title')} ({b['book_id']}) — source `{b.get('filename')}` → book index `{b['_md']}` · visual index `{b['_vis']}` · "
                     f"JSON `{b['_json']}` · text layer `{b.get('text_layer')}` · completeness **{(b.get('completeness') or {}).get('status', '?')}**")
        L.append(f"\nCounts: {len(books)} books · {sum(len(b.get('chapters', [])) for b in books)} chapters · {nvis} visuals\n")
    L.append("## Tools\n")
    L.append("- `tools/ocr_pdf.py` — OCR a scanned PDF into a page-marked text layer\n- `tools/render_pages.py` — render PDF pages to PNG\n"
             "- `tools/build_indexes.py` — regenerate all generated files from the per-book JSON\n- `tools/verify_knowledge_base.py` — completeness/consistency checks\n")
    L.append("## Archive\n\n- `_archive/v1_2026-10-06_studyplusplus_scans/` — the first index built from the earlier watermarked scans (replaced; not authoritative).\n")
    L.append("## Validation Status\n\nSee the bottom of this file (appended by `tools/verify_knowledge_base.py`).\n")
    return "\n".join(L) + "\n"


def main():
    data = {}
    for cls in (11, 12):
        books = load_class(cls)
        if not books:
            print(f"no books for class {cls}")
            continue
        for s in sorted({b["_subject"] for b in books}):
            write(os.path.join(ROOT, "indexes", f"class_{cls}", s, f"{s}_subject_index.md"),
                  build_subject_index(cls, s, [b for b in books if b["_subject"] == s]))
        vis, nvis = build_visual_index(cls, books)
        write(os.path.join(ROOT, "indexes", f"class_{cls}", f"class_{cls}_visual_index.md"), vis)
        write(os.path.join(ROOT, "indexes", f"class_{cls}", f"class_{cls}_assessment_index.md"), build_assessment_index(cls, books))
        write(os.path.join(ROOT, f"Class_{cls}_Master_Index.md"), build_master(cls, books, nvis))
        km = {"class": cls, "generated": DATE, "books": [{k: v for k, v in b.items() if not k.startswith("_")} for b in books]}
        with open(os.path.join(ROOT, "indexes", f"class_{cls}", f"class_{cls}_knowledge_map.json"), "w", encoding="utf-8") as f:
            json.dump(km, f, ensure_ascii=False, indent=1)
        print("wrote", f"indexes/class_{cls}/class_{cls}_knowledge_map.json")
        data[cls] = (books, nvis)
        for b in books:
            print(f"  {b['book_id']}: {len(b.get('chapters', []))} ch, "
                  f"{sum(1 for ch in b.get('chapters', []) for d, t in walk(ch.get('topics')) if tid(t))} topics, "
                  f"{sum(len(ch.get('visuals') or []) for ch in b.get('chapters', []))} visuals, "
                  f"{sum(sum(qcount(ch).values()) for ch in b.get('chapters', []))} questions")
    if len(data) == 2:
        write(os.path.join(ROOT, "Academic_Library_Index_Manifest.md"), build_manifest(data))


if __name__ == "__main__":
    main()
